//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities_acd : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities_acd”部分中的连接字符串初始化新 testEntities_acd 对象。
        /// </summary>
        public testEntities_acd() : base("name=testEntities_acd", "testEntities_acd")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_acd 对象。
        /// </summary>
        public testEntities_acd(string connectionString) : base(connectionString, "testEntities_acd")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_acd 对象。
        /// </summary>
        public testEntities_acd(EntityConnection connection) : base(connection, "testEntities_acd")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_acd2> crm_aspect_monitor_acd2
        {
            get
            {
                if ((_crm_aspect_monitor_acd2 == null))
                {
                    _crm_aspect_monitor_acd2 = base.CreateObjectSet<crm_aspect_monitor_acd2>("crm_aspect_monitor_acd2");
                }
                return _crm_aspect_monitor_acd2;
            }
        }
        private ObjectSet<crm_aspect_monitor_acd2> _crm_aspect_monitor_acd2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_acd2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_acd2(crm_aspect_monitor_acd2 crm_aspect_monitor_acd2)
        {
            base.AddObject("crm_aspect_monitor_acd2", crm_aspect_monitor_acd2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="crm_aspect_monitor_acd2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_acd2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_acd2 对象。
        /// </summary>
        /// <param name="serviceId">serviceId 属性的初始值。</param>
        public static crm_aspect_monitor_acd2 Createcrm_aspect_monitor_acd2(global::System.String serviceId)
        {
            crm_aspect_monitor_acd2 crm_aspect_monitor_acd2 = new crm_aspect_monitor_acd2();
            crm_aspect_monitor_acd2.serviceId = serviceId;
            return crm_aspect_monitor_acd2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serviceId
        {
            get
            {
                return _serviceId;
            }
            set
            {
                if (_serviceId != value)
                {
                    OnserviceIdChanging(value);
                    ReportPropertyChanging("serviceId");
                    _serviceId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("serviceId");
                    OnserviceIdChanged();
                }
            }
        }
        private global::System.String _serviceId;
        partial void OnserviceIdChanging(global::System.String value);
        partial void OnserviceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInAccept
        {
            get
            {
                return _agentsInAccept;
            }
            set
            {
                OnagentsInAcceptChanging(value);
                ReportPropertyChanging("agentsInAccept");
                _agentsInAccept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInAccept");
                OnagentsInAcceptChanged();
            }
        }
        private global::System.String _agentsInAccept;
        partial void OnagentsInAcceptChanging(global::System.String value);
        partial void OnagentsInAcceptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInActive
        {
            get
            {
                return _agentsInActive;
            }
            set
            {
                OnagentsInActiveChanging(value);
                ReportPropertyChanging("agentsInActive");
                _agentsInActive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInActive");
                OnagentsInActiveChanged();
            }
        }
        private global::System.String _agentsInActive;
        partial void OnagentsInActiveChanging(global::System.String value);
        partial void OnagentsInActiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInConnect
        {
            get
            {
                return _agentsInConnect;
            }
            set
            {
                OnagentsInConnectChanging(value);
                ReportPropertyChanging("agentsInConnect");
                _agentsInConnect = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInConnect");
                OnagentsInConnectChanged();
            }
        }
        private global::System.String _agentsInConnect;
        partial void OnagentsInConnectChanging(global::System.String value);
        partial void OnagentsInConnectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInHold
        {
            get
            {
                return _agentsInHold;
            }
            set
            {
                OnagentsInHoldChanging(value);
                ReportPropertyChanging("agentsInHold");
                _agentsInHold = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInHold");
                OnagentsInHoldChanged();
            }
        }
        private global::System.String _agentsInHold;
        partial void OnagentsInHoldChanging(global::System.String value);
        partial void OnagentsInHoldChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInIdle
        {
            get
            {
                return _agentsInIdle;
            }
            set
            {
                OnagentsInIdleChanging(value);
                ReportPropertyChanging("agentsInIdle");
                _agentsInIdle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInIdle");
                OnagentsInIdleChanged();
            }
        }
        private global::System.String _agentsInIdle;
        partial void OnagentsInIdleChanging(global::System.String value);
        partial void OnagentsInIdleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInInternal
        {
            get
            {
                return _agentsInInternal;
            }
            set
            {
                OnagentsInInternalChanging(value);
                ReportPropertyChanging("agentsInInternal");
                _agentsInInternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInInternal");
                OnagentsInInternalChanged();
            }
        }
        private global::System.String _agentsInInternal;
        partial void OnagentsInInternalChanging(global::System.String value);
        partial void OnagentsInInternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInManual
        {
            get
            {
                return _agentsInManual;
            }
            set
            {
                OnagentsInManualChanging(value);
                ReportPropertyChanging("agentsInManual");
                _agentsInManual = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInManual");
                OnagentsInManualChanged();
            }
        }
        private global::System.String _agentsInManual;
        partial void OnagentsInManualChanging(global::System.String value);
        partial void OnagentsInManualChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInMultil
        {
            get
            {
                return _agentsInMultil;
            }
            set
            {
                OnagentsInMultilChanging(value);
                ReportPropertyChanging("agentsInMultil");
                _agentsInMultil = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInMultil");
                OnagentsInMultilChanged();
            }
        }
        private global::System.String _agentsInMultil;
        partial void OnagentsInMultilChanging(global::System.String value);
        partial void OnagentsInMultilChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInNotReady
        {
            get
            {
                return _agentsInNotReady;
            }
            set
            {
                OnagentsInNotReadyChanging(value);
                ReportPropertyChanging("agentsInNotReady");
                _agentsInNotReady = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInNotReady");
                OnagentsInNotReadyChanged();
            }
        }
        private global::System.String _agentsInNotReady;
        partial void OnagentsInNotReadyChanging(global::System.String value);
        partial void OnagentsInNotReadyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInOther
        {
            get
            {
                return _agentsInOther;
            }
            set
            {
                OnagentsInOtherChanging(value);
                ReportPropertyChanging("agentsInOther");
                _agentsInOther = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInOther");
                OnagentsInOtherChanged();
            }
        }
        private global::System.String _agentsInOther;
        partial void OnagentsInOtherChanging(global::System.String value);
        partial void OnagentsInOtherChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInPark
        {
            get
            {
                return _agentsInPark;
            }
            set
            {
                OnagentsInParkChanging(value);
                ReportPropertyChanging("agentsInPark");
                _agentsInPark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInPark");
                OnagentsInParkChanged();
            }
        }
        private global::System.String _agentsInPark;
        partial void OnagentsInParkChanging(global::System.String value);
        partial void OnagentsInParkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInPreview
        {
            get
            {
                return _agentsInPreview;
            }
            set
            {
                OnagentsInPreviewChanging(value);
                ReportPropertyChanging("agentsInPreview");
                _agentsInPreview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInPreview");
                OnagentsInPreviewChanged();
            }
        }
        private global::System.String _agentsInPreview;
        partial void OnagentsInPreviewChanging(global::System.String value);
        partial void OnagentsInPreviewChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInWrap
        {
            get
            {
                return _agentsInWrap;
            }
            set
            {
                OnagentsInWrapChanging(value);
                ReportPropertyChanging("agentsInWrap");
                _agentsInWrap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInWrap");
                OnagentsInWrapChanged();
            }
        }
        private global::System.String _agentsInWrap;
        partial void OnagentsInWrapChanging(global::System.String value);
        partial void OnagentsInWrapChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsLoggedIn
        {
            get
            {
                return _agentsLoggedIn;
            }
            set
            {
                OnagentsLoggedInChanging(value);
                ReportPropertyChanging("agentsLoggedIn");
                _agentsLoggedIn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsLoggedIn");
                OnagentsLoggedInChanged();
            }
        }
        private global::System.String _agentsLoggedIn;
        partial void OnagentsLoggedInChanging(global::System.String value);
        partial void OnagentsLoggedInChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application
        {
            get
            {
                return _application;
            }
            set
            {
                OnapplicationChanging(value);
                ReportPropertyChanging("application");
                _application = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application");
                OnapplicationChanged();
            }
        }
        private global::System.String _application;
        partial void OnapplicationChanging(global::System.String value);
        partial void OnapplicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.String _applicationId;
        partial void OnapplicationIdChanging(global::System.String value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentActiveTime
        {
            get
            {
                return _avgAgentActiveTime;
            }
            set
            {
                OnavgAgentActiveTimeChanging(value);
                ReportPropertyChanging("avgAgentActiveTime");
                _avgAgentActiveTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentActiveTime");
                OnavgAgentActiveTimeChanged();
            }
        }
        private global::System.String _avgAgentActiveTime;
        partial void OnavgAgentActiveTimeChanging(global::System.String value);
        partial void OnavgAgentActiveTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentIdleTime
        {
            get
            {
                return _avgAgentIdleTime;
            }
            set
            {
                OnavgAgentIdleTimeChanging(value);
                ReportPropertyChanging("avgAgentIdleTime");
                _avgAgentIdleTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentIdleTime");
                OnavgAgentIdleTimeChanged();
            }
        }
        private global::System.String _avgAgentIdleTime;
        partial void OnavgAgentIdleTimeChanging(global::System.String value);
        partial void OnavgAgentIdleTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentWrapTime
        {
            get
            {
                return _avgAgentWrapTime;
            }
            set
            {
                OnavgAgentWrapTimeChanging(value);
                ReportPropertyChanging("avgAgentWrapTime");
                _avgAgentWrapTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentWrapTime");
                OnavgAgentWrapTimeChanged();
            }
        }
        private global::System.String _avgAgentWrapTime;
        partial void OnavgAgentWrapTimeChanging(global::System.String value);
        partial void OnavgAgentWrapTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgSpeedOfAnswer
        {
            get
            {
                return _avgSpeedOfAnswer;
            }
            set
            {
                OnavgSpeedOfAnswerChanging(value);
                ReportPropertyChanging("avgSpeedOfAnswer");
                _avgSpeedOfAnswer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgSpeedOfAnswer");
                OnavgSpeedOfAnswerChanged();
            }
        }
        private global::System.String _avgSpeedOfAnswer;
        partial void OnavgSpeedOfAnswerChanging(global::System.String value);
        partial void OnavgSpeedOfAnswerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgTimeInQueue
        {
            get
            {
                return _avgTimeInQueue;
            }
            set
            {
                OnavgTimeInQueueChanging(value);
                ReportPropertyChanging("avgTimeInQueue");
                _avgTimeInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgTimeInQueue");
                OnavgTimeInQueueChanged();
            }
        }
        private global::System.String _avgTimeInQueue;
        partial void OnavgTimeInQueueChanging(global::System.String value);
        partial void OnavgTimeInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgTimeToAbandon
        {
            get
            {
                return _avgTimeToAbandon;
            }
            set
            {
                OnavgTimeToAbandonChanging(value);
                ReportPropertyChanging("avgTimeToAbandon");
                _avgTimeToAbandon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgTimeToAbandon");
                OnavgTimeToAbandonChanged();
            }
        }
        private global::System.String _avgTimeToAbandon;
        partial void OnavgTimeToAbandonChanging(global::System.String value);
        partial void OnavgTimeToAbandonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgWaitTime
        {
            get
            {
                return _avgWaitTime;
            }
            set
            {
                OnavgWaitTimeChanging(value);
                ReportPropertyChanging("avgWaitTime");
                _avgWaitTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgWaitTime");
                OnavgWaitTimeChanged();
            }
        }
        private global::System.String _avgWaitTime;
        partial void OnavgWaitTimeChanging(global::System.String value);
        partial void OnavgWaitTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedBeforeQueue
        {
            get
            {
                return _callsAbandonedBeforeQueue;
            }
            set
            {
                OncallsAbandonedBeforeQueueChanging(value);
                ReportPropertyChanging("callsAbandonedBeforeQueue");
                _callsAbandonedBeforeQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedBeforeQueue");
                OncallsAbandonedBeforeQueueChanged();
            }
        }
        private global::System.String _callsAbandonedBeforeQueue;
        partial void OncallsAbandonedBeforeQueueChanging(global::System.String value);
        partial void OncallsAbandonedBeforeQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedBeforeServiceLevelInterval
        {
            get
            {
                return _callsAbandonedBeforeServiceLevelInterval;
            }
            set
            {
                OncallsAbandonedBeforeServiceLevelIntervalChanging(value);
                ReportPropertyChanging("callsAbandonedBeforeServiceLevelInterval");
                _callsAbandonedBeforeServiceLevelInterval = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedBeforeServiceLevelInterval");
                OncallsAbandonedBeforeServiceLevelIntervalChanged();
            }
        }
        private global::System.String _callsAbandonedBeforeServiceLevelInterval;
        partial void OncallsAbandonedBeforeServiceLevelIntervalChanging(global::System.String value);
        partial void OncallsAbandonedBeforeServiceLevelIntervalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedBeforeServiceLevelIntervalDaily
        {
            get
            {
                return _callsAbandonedBeforeServiceLevelIntervalDaily;
            }
            set
            {
                OncallsAbandonedBeforeServiceLevelIntervalDailyChanging(value);
                ReportPropertyChanging("callsAbandonedBeforeServiceLevelIntervalDaily");
                _callsAbandonedBeforeServiceLevelIntervalDaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedBeforeServiceLevelIntervalDaily");
                OncallsAbandonedBeforeServiceLevelIntervalDailyChanged();
            }
        }
        private global::System.String _callsAbandonedBeforeServiceLevelIntervalDaily;
        partial void OncallsAbandonedBeforeServiceLevelIntervalDailyChanging(global::System.String value);
        partial void OncallsAbandonedBeforeServiceLevelIntervalDailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedBeforeShortCallInterval
        {
            get
            {
                return _callsAbandonedBeforeShortCallInterval;
            }
            set
            {
                OncallsAbandonedBeforeShortCallIntervalChanging(value);
                ReportPropertyChanging("callsAbandonedBeforeShortCallInterval");
                _callsAbandonedBeforeShortCallInterval = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedBeforeShortCallInterval");
                OncallsAbandonedBeforeShortCallIntervalChanged();
            }
        }
        private global::System.String _callsAbandonedBeforeShortCallInterval;
        partial void OncallsAbandonedBeforeShortCallIntervalChanging(global::System.String value);
        partial void OncallsAbandonedBeforeShortCallIntervalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedBeforeShortCallIntervalDaily
        {
            get
            {
                return _callsAbandonedBeforeShortCallIntervalDaily;
            }
            set
            {
                OncallsAbandonedBeforeShortCallIntervalDailyChanging(value);
                ReportPropertyChanging("callsAbandonedBeforeShortCallIntervalDaily");
                _callsAbandonedBeforeShortCallIntervalDaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedBeforeShortCallIntervalDaily");
                OncallsAbandonedBeforeShortCallIntervalDailyChanged();
            }
        }
        private global::System.String _callsAbandonedBeforeShortCallIntervalDaily;
        partial void OncallsAbandonedBeforeShortCallIntervalDailyChanging(global::System.String value);
        partial void OncallsAbandonedBeforeShortCallIntervalDailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedInQueue
        {
            get
            {
                return _callsAbandonedInQueue;
            }
            set
            {
                OncallsAbandonedInQueueChanging(value);
                ReportPropertyChanging("callsAbandonedInQueue");
                _callsAbandonedInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedInQueue");
                OncallsAbandonedInQueueChanged();
            }
        }
        private global::System.String _callsAbandonedInQueue;
        partial void OncallsAbandonedInQueueChanging(global::System.String value);
        partial void OncallsAbandonedInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedTotal
        {
            get
            {
                return _callsAbandonedTotal;
            }
            set
            {
                OncallsAbandonedTotalChanging(value);
                ReportPropertyChanging("callsAbandonedTotal");
                _callsAbandonedTotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedTotal");
                OncallsAbandonedTotalChanged();
            }
        }
        private global::System.String _callsAbandonedTotal;
        partial void OncallsAbandonedTotalChanging(global::System.String value);
        partial void OncallsAbandonedTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAbandonedTotalDaily
        {
            get
            {
                return _callsAbandonedTotalDaily;
            }
            set
            {
                OncallsAbandonedTotalDailyChanging(value);
                ReportPropertyChanging("callsAbandonedTotalDaily");
                _callsAbandonedTotalDaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAbandonedTotalDaily");
                OncallsAbandonedTotalDailyChanged();
            }
        }
        private global::System.String _callsAbandonedTotalDaily;
        partial void OncallsAbandonedTotalDailyChanging(global::System.String value);
        partial void OncallsAbandonedTotalDailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAnswered
        {
            get
            {
                return _callsAnswered;
            }
            set
            {
                OncallsAnsweredChanging(value);
                ReportPropertyChanging("callsAnswered");
                _callsAnswered = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAnswered");
                OncallsAnsweredChanged();
            }
        }
        private global::System.String _callsAnswered;
        partial void OncallsAnsweredChanging(global::System.String value);
        partial void OncallsAnsweredChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsInProgress
        {
            get
            {
                return _callsInProgress;
            }
            set
            {
                OncallsInProgressChanging(value);
                ReportPropertyChanging("callsInProgress");
                _callsInProgress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsInProgress");
                OncallsInProgressChanged();
            }
        }
        private global::System.String _callsInProgress;
        partial void OncallsInProgressChanging(global::System.String value);
        partial void OncallsInProgressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsInQueue
        {
            get
            {
                return _callsInQueue;
            }
            set
            {
                OncallsInQueueChanging(value);
                ReportPropertyChanging("callsInQueue");
                _callsInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsInQueue");
                OncallsInQueueChanged();
            }
        }
        private global::System.String _callsInQueue;
        partial void OncallsInQueueChanging(global::System.String value);
        partial void OncallsInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsInVoiceMail
        {
            get
            {
                return _callsInVoiceMail;
            }
            set
            {
                OncallsInVoiceMailChanging(value);
                ReportPropertyChanging("callsInVoiceMail");
                _callsInVoiceMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsInVoiceMail");
                OncallsInVoiceMailChanged();
            }
        }
        private global::System.String _callsInVoiceMail;
        partial void OncallsInVoiceMailChanging(global::System.String value);
        partial void OncallsInVoiceMailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsOffered
        {
            get
            {
                return _callsOffered;
            }
            set
            {
                OncallsOfferedChanging(value);
                ReportPropertyChanging("callsOffered");
                _callsOffered = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsOffered");
                OncallsOfferedChanged();
            }
        }
        private global::System.String _callsOffered;
        partial void OncallsOfferedChanging(global::System.String value);
        partial void OncallsOfferedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsOfferedServiceLevelInterval
        {
            get
            {
                return _callsOfferedServiceLevelInterval;
            }
            set
            {
                OncallsOfferedServiceLevelIntervalChanging(value);
                ReportPropertyChanging("callsOfferedServiceLevelInterval");
                _callsOfferedServiceLevelInterval = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsOfferedServiceLevelInterval");
                OncallsOfferedServiceLevelIntervalChanged();
            }
        }
        private global::System.String _callsOfferedServiceLevelInterval;
        partial void OncallsOfferedServiceLevelIntervalChanging(global::System.String value);
        partial void OncallsOfferedServiceLevelIntervalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsOverflowed
        {
            get
            {
                return _callsOverflowed;
            }
            set
            {
                OncallsOverflowedChanging(value);
                ReportPropertyChanging("callsOverflowed");
                _callsOverflowed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsOverflowed");
                OncallsOverflowedChanged();
            }
        }
        private global::System.String _callsOverflowed;
        partial void OncallsOverflowedChanging(global::System.String value);
        partial void OncallsOverflowedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsRejected
        {
            get
            {
                return _callsRejected;
            }
            set
            {
                OncallsRejectedChanging(value);
                ReportPropertyChanging("callsRejected");
                _callsRejected = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsRejected");
                OncallsRejectedChanged();
            }
        }
        private global::System.String _callsRejected;
        partial void OncallsRejectedChanging(global::System.String value);
        partial void OncallsRejectedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsRerouted
        {
            get
            {
                return _callsRerouted;
            }
            set
            {
                OncallsReroutedChanging(value);
                ReportPropertyChanging("callsRerouted");
                _callsRerouted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsRerouted");
                OncallsReroutedChanged();
            }
        }
        private global::System.String _callsRerouted;
        partial void OncallsReroutedChanging(global::System.String value);
        partial void OncallsReroutedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsServicedWithinServiceLevel
        {
            get
            {
                return _callsServicedWithinServiceLevel;
            }
            set
            {
                OncallsServicedWithinServiceLevelChanging(value);
                ReportPropertyChanging("callsServicedWithinServiceLevel");
                _callsServicedWithinServiceLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsServicedWithinServiceLevel");
                OncallsServicedWithinServiceLevelChanged();
            }
        }
        private global::System.String _callsServicedWithinServiceLevel;
        partial void OncallsServicedWithinServiceLevelChanging(global::System.String value);
        partial void OncallsServicedWithinServiceLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsServicedWithinServiceLevelDaily
        {
            get
            {
                return _callsServicedWithinServiceLevelDaily;
            }
            set
            {
                OncallsServicedWithinServiceLevelDailyChanging(value);
                ReportPropertyChanging("callsServicedWithinServiceLevelDaily");
                _callsServicedWithinServiceLevelDaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsServicedWithinServiceLevelDaily");
                OncallsServicedWithinServiceLevelDailyChanged();
            }
        }
        private global::System.String _callsServicedWithinServiceLevelDaily;
        partial void OncallsServicedWithinServiceLevelDailyChanging(global::System.String value);
        partial void OncallsServicedWithinServiceLevelDailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToAgent
        {
            get
            {
                return _callsTransferredToAgent;
            }
            set
            {
                OncallsTransferredToAgentChanging(value);
                ReportPropertyChanging("callsTransferredToAgent");
                _callsTransferredToAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToAgent");
                OncallsTransferredToAgentChanged();
            }
        }
        private global::System.String _callsTransferredToAgent;
        partial void OncallsTransferredToAgentChanging(global::System.String value);
        partial void OncallsTransferredToAgentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToExternal
        {
            get
            {
                return _callsTransferredToExternal;
            }
            set
            {
                OncallsTransferredToExternalChanging(value);
                ReportPropertyChanging("callsTransferredToExternal");
                _callsTransferredToExternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToExternal");
                OncallsTransferredToExternalChanged();
            }
        }
        private global::System.String _callsTransferredToExternal;
        partial void OncallsTransferredToExternalChanging(global::System.String value);
        partial void OncallsTransferredToExternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToService
        {
            get
            {
                return _callsTransferredToService;
            }
            set
            {
                OncallsTransferredToServiceChanging(value);
                ReportPropertyChanging("callsTransferredToService");
                _callsTransferredToService = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToService");
                OncallsTransferredToServiceChanged();
            }
        }
        private global::System.String _callsTransferredToService;
        partial void OncallsTransferredToServiceChanging(global::System.String value);
        partial void OncallsTransferredToServiceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentLongestQueueWaitSeconds
        {
            get
            {
                return _currentLongestQueueWaitSeconds;
            }
            set
            {
                OncurrentLongestQueueWaitSecondsChanging(value);
                ReportPropertyChanging("currentLongestQueueWaitSeconds");
                _currentLongestQueueWaitSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentLongestQueueWaitSeconds");
                OncurrentLongestQueueWaitSecondsChanged();
            }
        }
        private global::System.String _currentLongestQueueWaitSeconds;
        partial void OncurrentLongestQueueWaitSecondsChanging(global::System.String value);
        partial void OncurrentLongestQueueWaitSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durActiveTime
        {
            get
            {
                return _durActiveTime;
            }
            set
            {
                OndurActiveTimeChanging(value);
                ReportPropertyChanging("durActiveTime");
                _durActiveTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durActiveTime");
                OndurActiveTimeChanged();
            }
        }
        private global::System.String _durActiveTime;
        partial void OndurActiveTimeChanging(global::System.String value);
        partial void OndurActiveTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durWrapTime
        {
            get
            {
                return _durWrapTime;
            }
            set
            {
                OndurWrapTimeChanging(value);
                ReportPropertyChanging("durWrapTime");
                _durWrapTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durWrapTime");
                OndurWrapTimeChanged();
            }
        }
        private global::System.String _durWrapTime;
        partial void OndurWrapTimeChanging(global::System.String value);
        partial void OndurWrapTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxCallsInQueue
        {
            get
            {
                return _maxCallsInQueue;
            }
            set
            {
                OnmaxCallsInQueueChanging(value);
                ReportPropertyChanging("maxCallsInQueue");
                _maxCallsInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxCallsInQueue");
                OnmaxCallsInQueueChanged();
            }
        }
        private global::System.String _maxCallsInQueue;
        partial void OnmaxCallsInQueueChanging(global::System.String value);
        partial void OnmaxCallsInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxWaitInQueue
        {
            get
            {
                return _maxWaitInQueue;
            }
            set
            {
                OnmaxWaitInQueueChanging(value);
                ReportPropertyChanging("maxWaitInQueue");
                _maxWaitInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxWaitInQueue");
                OnmaxWaitInQueueChanged();
            }
        }
        private global::System.String _maxWaitInQueue;
        partial void OnmaxWaitInQueueChanging(global::System.String value);
        partial void OnmaxWaitInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String occupancy
        {
            get
            {
                return _occupancy;
            }
            set
            {
                OnoccupancyChanging(value);
                ReportPropertyChanging("occupancy");
                _occupancy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("occupancy");
                OnoccupancyChanged();
            }
        }
        private global::System.String _occupancy;
        partial void OnoccupancyChanging(global::System.String value);
        partial void OnoccupancyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String percentServiceWithinServiceLevel
        {
            get
            {
                return _percentServiceWithinServiceLevel;
            }
            set
            {
                OnpercentServiceWithinServiceLevelChanging(value);
                ReportPropertyChanging("percentServiceWithinServiceLevel");
                _percentServiceWithinServiceLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("percentServiceWithinServiceLevel");
                OnpercentServiceWithinServiceLevelChanged();
            }
        }
        private global::System.String _percentServiceWithinServiceLevel;
        partial void OnpercentServiceWithinServiceLevelChanging(global::System.String value);
        partial void OnpercentServiceWithinServiceLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceLevelCalculationMethod
        {
            get
            {
                return _serviceLevelCalculationMethod;
            }
            set
            {
                OnserviceLevelCalculationMethodChanging(value);
                ReportPropertyChanging("serviceLevelCalculationMethod");
                _serviceLevelCalculationMethod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceLevelCalculationMethod");
                OnserviceLevelCalculationMethodChanged();
            }
        }
        private global::System.String _serviceLevelCalculationMethod;
        partial void OnserviceLevelCalculationMethodChanging(global::System.String value);
        partial void OnserviceLevelCalculationMethodChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceType
        {
            get
            {
                return _serviceType;
            }
            set
            {
                OnserviceTypeChanging(value);
                ReportPropertyChanging("serviceType");
                _serviceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceType");
                OnserviceTypeChanged();
            }
        }
        private global::System.String _serviceType;
        partial void OnserviceTypeChanging(global::System.String value);
        partial void OnserviceTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceTypeId
        {
            get
            {
                return _serviceTypeId;
            }
            set
            {
                OnserviceTypeIdChanging(value);
                ReportPropertyChanging("serviceTypeId");
                _serviceTypeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceTypeId");
                OnserviceTypeIdChanged();
            }
        }
        private global::System.String _serviceTypeId;
        partial void OnserviceTypeIdChanging(global::System.String value);
        partial void OnserviceTypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String startTimeMilitary
        {
            get
            {
                return _startTimeMilitary;
            }
            set
            {
                OnstartTimeMilitaryChanging(value);
                ReportPropertyChanging("startTimeMilitary");
                _startTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("startTimeMilitary");
                OnstartTimeMilitaryChanged();
            }
        }
        private global::System.String _startTimeMilitary;
        partial void OnstartTimeMilitaryChanging(global::System.String value);
        partial void OnstartTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.String _statusId;
        partial void OnstatusIdChanging(global::System.String value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stopTimeMilitary
        {
            get
            {
                return _stopTimeMilitary;
            }
            set
            {
                OnstopTimeMilitaryChanging(value);
                ReportPropertyChanging("stopTimeMilitary");
                _stopTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stopTimeMilitary");
                OnstopTimeMilitaryChanged();
            }
        }
        private global::System.String _stopTimeMilitary;
        partial void OnstopTimeMilitaryChanging(global::System.String value);
        partial void OnstopTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneIdentifier
        {
            get
            {
                return _timezoneIdentifier;
            }
            set
            {
                OntimezoneIdentifierChanging(value);
                ReportPropertyChanging("timezoneIdentifier");
                _timezoneIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneIdentifier");
                OntimezoneIdentifierChanged();
            }
        }
        private global::System.String _timezoneIdentifier;
        partial void OntimezoneIdentifierChanging(global::System.String value);
        partial void OntimezoneIdentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String totalQueuedTime
        {
            get
            {
                return _totalQueuedTime;
            }
            set
            {
                OntotalQueuedTimeChanging(value);
                ReportPropertyChanging("totalQueuedTime");
                _totalQueuedTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("totalQueuedTime");
                OntotalQueuedTimeChanged();
            }
        }
        private global::System.String _totalQueuedTime;
        partial void OntotalQueuedTimeChanging(global::System.String value);
        partial void OntotalQueuedTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String totalRoutedToUser
        {
            get
            {
                return _totalRoutedToUser;
            }
            set
            {
                OntotalRoutedToUserChanging(value);
                ReportPropertyChanging("totalRoutedToUser");
                _totalRoutedToUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("totalRoutedToUser");
                OntotalRoutedToUserChanged();
            }
        }
        private global::System.String _totalRoutedToUser;
        partial void OntotalRoutedToUserChanging(global::System.String value);
        partial void OntotalRoutedToUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String totalTimeToService
        {
            get
            {
                return _totalTimeToService;
            }
            set
            {
                OntotalTimeToServiceChanging(value);
                ReportPropertyChanging("totalTimeToService");
                _totalTimeToService = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("totalTimeToService");
                OntotalTimeToServiceChanged();
            }
        }
        private global::System.String _totalTimeToService;
        partial void OntotalTimeToServiceChanging(global::System.String value);
        partial void OntotalTimeToServiceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStartTime
        {
            get
            {
                return _utcStartTime;
            }
            set
            {
                OnutcStartTimeChanging(value);
                ReportPropertyChanging("utcStartTime");
                _utcStartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStartTime");
                OnutcStartTimeChanged();
            }
        }
        private global::System.String _utcStartTime;
        partial void OnutcStartTimeChanging(global::System.String value);
        partial void OnutcStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStopTime
        {
            get
            {
                return _utcStopTime;
            }
            set
            {
                OnutcStopTimeChanging(value);
                ReportPropertyChanging("utcStopTime");
                _utcStopTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStopTime");
                OnutcStopTimeChanged();
            }
        }
        private global::System.String _utcStopTime;
        partial void OnutcStopTimeChanging(global::System.String value);
        partial void OnutcStopTimeChanged();

        #endregion

    
    }

    #endregion

    
}
