//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities_agentpri : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities_agentpri”部分中的连接字符串初始化新 testEntities_agentpri 对象。
        /// </summary>
        public testEntities_agentpri() : base("name=testEntities_agentpri", "testEntities_agentpri")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_agentpri 对象。
        /// </summary>
        public testEntities_agentpri(string connectionString) : base(connectionString, "testEntities_agentpri")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_agentpri 对象。
        /// </summary>
        public testEntities_agentpri(EntityConnection connection) : base(connection, "testEntities_agentpri")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_agent2> crm_aspect_monitor_agent2
        {
            get
            {
                if ((_crm_aspect_monitor_agent2 == null))
                {
                    _crm_aspect_monitor_agent2 = base.CreateObjectSet<crm_aspect_monitor_agent2>("crm_aspect_monitor_agent2");
                }
                return _crm_aspect_monitor_agent2;
            }
        }
        private ObjectSet<crm_aspect_monitor_agent2> _crm_aspect_monitor_agent2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_agent2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_agent2(crm_aspect_monitor_agent2 crm_aspect_monitor_agent2)
        {
            base.AddObject("crm_aspect_monitor_agent2", crm_aspect_monitor_agent2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel2", Name="crm_aspect_monitor_agent2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_agent2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_agent2 对象。
        /// </summary>
        /// <param name="primaryId">primaryId 属性的初始值。</param>
        public static crm_aspect_monitor_agent2 Createcrm_aspect_monitor_agent2(global::System.Int32 primaryId)
        {
            crm_aspect_monitor_agent2 crm_aspect_monitor_agent2 = new crm_aspect_monitor_agent2();
            crm_aspect_monitor_agent2.primaryId = primaryId;
            return crm_aspect_monitor_agent2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.String _userId;
        partial void OnuserIdChanging(global::System.String value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceId
        {
            get
            {
                return _serviceId;
            }
            set
            {
                OnserviceIdChanging(value);
                ReportPropertyChanging("serviceId");
                _serviceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceId");
                OnserviceIdChanged();
            }
        }
        private global::System.String _serviceId;
        partial void OnserviceIdChanging(global::System.String value);
        partial void OnserviceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceType
        {
            get
            {
                return _serviceType;
            }
            set
            {
                OnserviceTypeChanging(value);
                ReportPropertyChanging("serviceType");
                _serviceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceType");
                OnserviceTypeChanged();
            }
        }
        private global::System.String _serviceType;
        partial void OnserviceTypeChanging(global::System.String value);
        partial void OnserviceTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceTypeId
        {
            get
            {
                return _serviceTypeId;
            }
            set
            {
                OnserviceTypeIdChanging(value);
                ReportPropertyChanging("serviceTypeId");
                _serviceTypeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceTypeId");
                OnserviceTypeIdChanged();
            }
        }
        private global::System.String _serviceTypeId;
        partial void OnserviceTypeIdChanging(global::System.String value);
        partial void OnserviceTypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.String _statusId;
        partial void OnstatusIdChanging(global::System.String value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptCalls
        {
            get
            {
                return _acceptCalls;
            }
            set
            {
                OnacceptCallsChanging(value);
                ReportPropertyChanging("acceptCalls");
                _acceptCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptCalls");
                OnacceptCallsChanged();
            }
        }
        private global::System.String _acceptCalls;
        partial void OnacceptCallsChanging(global::System.String value);
        partial void OnacceptCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptSeconds
        {
            get
            {
                return _acceptSeconds;
            }
            set
            {
                OnacceptSecondsChanging(value);
                ReportPropertyChanging("acceptSeconds");
                _acceptSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptSeconds");
                OnacceptSecondsChanged();
            }
        }
        private global::System.String _acceptSeconds;
        partial void OnacceptSecondsChanging(global::System.String value);
        partial void OnacceptSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acdCalls
        {
            get
            {
                return _acdCalls;
            }
            set
            {
                OnacdCallsChanging(value);
                ReportPropertyChanging("acdCalls");
                _acdCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acdCalls");
                OnacdCallsChanged();
            }
        }
        private global::System.String _acdCalls;
        partial void OnacdCallsChanging(global::System.String value);
        partial void OnacdCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String activeSeconds
        {
            get
            {
                return _activeSeconds;
            }
            set
            {
                OnactiveSecondsChanging(value);
                ReportPropertyChanging("activeSeconds");
                _activeSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("activeSeconds");
                OnactiveSecondsChanged();
            }
        }
        private global::System.String _activeSeconds;
        partial void OnactiveSecondsChanging(global::System.String value);
        partial void OnactiveSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agdCalls
        {
            get
            {
                return _agdCalls;
            }
            set
            {
                OnagdCallsChanging(value);
                ReportPropertyChanging("agdCalls");
                _agdCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agdCalls");
                OnagdCallsChanged();
            }
        }
        private global::System.String _agdCalls;
        partial void OnagdCallsChanging(global::System.String value);
        partial void OnagdCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentIndex
        {
            get
            {
                return _agentIndex;
            }
            set
            {
                OnagentIndexChanging(value);
                ReportPropertyChanging("agentIndex");
                _agentIndex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentIndex");
                OnagentIndexChanged();
            }
        }
        private global::System.String _agentIndex;
        partial void OnagentIndexChanging(global::System.String value);
        partial void OnagentIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aodCalls
        {
            get
            {
                return _aodCalls;
            }
            set
            {
                OnaodCallsChanging(value);
                ReportPropertyChanging("aodCalls");
                _aodCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aodCalls");
                OnaodCallsChanged();
            }
        }
        private global::System.String _aodCalls;
        partial void OnaodCallsChanging(global::System.String value);
        partial void OnaodCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String audioPath
        {
            get
            {
                return _audioPath;
            }
            set
            {
                OnaudioPathChanging(value);
                ReportPropertyChanging("audioPath");
                _audioPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("audioPath");
                OnaudioPathChanged();
            }
        }
        private global::System.String _audioPath;
        partial void OnaudioPathChanging(global::System.String value);
        partial void OnaudioPathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String chatCalls
        {
            get
            {
                return _chatCalls;
            }
            set
            {
                OnchatCallsChanging(value);
                ReportPropertyChanging("chatCalls");
                _chatCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("chatCalls");
                OnchatCallsChanged();
            }
        }
        private global::System.String _chatCalls;
        partial void OnchatCallsChanging(global::System.String value);
        partial void OnchatCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String conferenceCalls
        {
            get
            {
                return _conferenceCalls;
            }
            set
            {
                OnconferenceCallsChanging(value);
                ReportPropertyChanging("conferenceCalls");
                _conferenceCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("conferenceCalls");
                OnconferenceCallsChanged();
            }
        }
        private global::System.String _conferenceCalls;
        partial void OnconferenceCallsChanging(global::System.String value);
        partial void OnconferenceCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String connectSeconds
        {
            get
            {
                return _connectSeconds;
            }
            set
            {
                OnconnectSecondsChanging(value);
                ReportPropertyChanging("connectSeconds");
                _connectSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("connectSeconds");
                OnconnectSecondsChanged();
            }
        }
        private global::System.String _connectSeconds;
        partial void OnconnectSecondsChanging(global::System.String value);
        partial void OnconnectSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String consultAtionCalls
        {
            get
            {
                return _consultAtionCalls;
            }
            set
            {
                OnconsultAtionCallsChanging(value);
                ReportPropertyChanging("consultAtionCalls");
                _consultAtionCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("consultAtionCalls");
                OnconsultAtionCallsChanged();
            }
        }
        private global::System.String _consultAtionCalls;
        partial void OnconsultAtionCallsChanging(global::System.String value);
        partial void OnconsultAtionCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ctiCalls
        {
            get
            {
                return _ctiCalls;
            }
            set
            {
                OnctiCallsChanging(value);
                ReportPropertyChanging("ctiCalls");
                _ctiCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ctiCalls");
                OnctiCallsChanged();
            }
        }
        private global::System.String _ctiCalls;
        partial void OnctiCallsChanging(global::System.String value);
        partial void OnctiCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentServiceId
        {
            get
            {
                return _currentServiceId;
            }
            set
            {
                OncurrentServiceIdChanging(value);
                ReportPropertyChanging("currentServiceId");
                _currentServiceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentServiceId");
                OncurrentServiceIdChanged();
            }
        }
        private global::System.String _currentServiceId;
        partial void OncurrentServiceIdChanging(global::System.String value);
        partial void OncurrentServiceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String didCalls
        {
            get
            {
                return _didCalls;
            }
            set
            {
                OndidCallsChanging(value);
                ReportPropertyChanging("didCalls");
                _didCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("didCalls");
                OndidCallsChanged();
            }
        }
        private global::System.String _didCalls;
        partial void OndidCallsChanging(global::System.String value);
        partial void OndidCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailCalls
        {
            get
            {
                return _emailCalls;
            }
            set
            {
                OnemailCallsChanging(value);
                ReportPropertyChanging("emailCalls");
                _emailCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailCalls");
                OnemailCallsChanged();
            }
        }
        private global::System.String _emailCalls;
        partial void OnemailCallsChanging(global::System.String value);
        partial void OnemailCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String heldCalls
        {
            get
            {
                return _heldCalls;
            }
            set
            {
                OnheldCallsChanging(value);
                ReportPropertyChanging("heldCalls");
                _heldCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("heldCalls");
                OnheldCallsChanged();
            }
        }
        private global::System.String _heldCalls;
        partial void OnheldCallsChanging(global::System.String value);
        partial void OnheldCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String heldSeconds
        {
            get
            {
                return _heldSeconds;
            }
            set
            {
                OnheldSecondsChanging(value);
                ReportPropertyChanging("heldSeconds");
                _heldSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("heldSeconds");
                OnheldSecondsChanged();
            }
        }
        private global::System.String _heldSeconds;
        partial void OnheldSecondsChanging(global::System.String value);
        partial void OnheldSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idleSeconds
        {
            get
            {
                return _idleSeconds;
            }
            set
            {
                OnidleSecondsChanging(value);
                ReportPropertyChanging("idleSeconds");
                _idleSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idleSeconds");
                OnidleSecondsChanged();
            }
        }
        private global::System.String _idleSeconds;
        partial void OnidleSecondsChanging(global::System.String value);
        partial void OnidleSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imCalls
        {
            get
            {
                return _imCalls;
            }
            set
            {
                OnimCallsChanging(value);
                ReportPropertyChanging("imCalls");
                _imCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imCalls");
                OnimCallsChanged();
            }
        }
        private global::System.String _imCalls;
        partial void OnimCallsChanging(global::System.String value);
        partial void OnimCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String internalCalls
        {
            get
            {
                return _internalCalls;
            }
            set
            {
                OninternalCallsChanging(value);
                ReportPropertyChanging("internalCalls");
                _internalCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("internalCalls");
                OninternalCallsChanged();
            }
        }
        private global::System.String _internalCalls;
        partial void OninternalCallsChanging(global::System.String value);
        partial void OninternalCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String internalSeconds
        {
            get
            {
                return _internalSeconds;
            }
            set
            {
                OninternalSecondsChanging(value);
                ReportPropertyChanging("internalSeconds");
                _internalSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("internalSeconds");
                OninternalSecondsChanged();
            }
        }
        private global::System.String _internalSeconds;
        partial void OninternalSecondsChanging(global::System.String value);
        partial void OninternalSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastDisposition
        {
            get
            {
                return _lastDisposition;
            }
            set
            {
                OnlastDispositionChanging(value);
                ReportPropertyChanging("lastDisposition");
                _lastDisposition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastDisposition");
                OnlastDispositionChanged();
            }
        }
        private global::System.String _lastDisposition;
        partial void OnlastDispositionChanging(global::System.String value);
        partial void OnlastDispositionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastDispositionId
        {
            get
            {
                return _lastDispositionId;
            }
            set
            {
                OnlastDispositionIdChanging(value);
                ReportPropertyChanging("lastDispositionId");
                _lastDispositionId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastDispositionId");
                OnlastDispositionIdChanged();
            }
        }
        private global::System.String _lastDispositionId;
        partial void OnlastDispositionIdChanging(global::System.String value);
        partial void OnlastDispositionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loggedInSeconds
        {
            get
            {
                return _loggedInSeconds;
            }
            set
            {
                OnloggedInSecondsChanging(value);
                ReportPropertyChanging("loggedInSeconds");
                _loggedInSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loggedInSeconds");
                OnloggedInSecondsChanged();
            }
        }
        private global::System.String _loggedInSeconds;
        partial void OnloggedInSecondsChanging(global::System.String value);
        partial void OnloggedInSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manualCalls
        {
            get
            {
                return _manualCalls;
            }
            set
            {
                OnmanualCallsChanging(value);
                ReportPropertyChanging("manualCalls");
                _manualCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manualCalls");
                OnmanualCallsChanged();
            }
        }
        private global::System.String _manualCalls;
        partial void OnmanualCallsChanging(global::System.String value);
        partial void OnmanualCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manualSeconds
        {
            get
            {
                return _manualSeconds;
            }
            set
            {
                OnmanualSecondsChanging(value);
                ReportPropertyChanging("manualSeconds");
                _manualSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manualSeconds");
                OnmanualSecondsChanged();
            }
        }
        private global::System.String _manualSeconds;
        partial void OnmanualSecondsChanging(global::System.String value);
        partial void OnmanualSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monitoringCalls
        {
            get
            {
                return _monitoringCalls;
            }
            set
            {
                OnmonitoringCallsChanging(value);
                ReportPropertyChanging("monitoringCalls");
                _monitoringCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monitoringCalls");
                OnmonitoringCallsChanged();
            }
        }
        private global::System.String _monitoringCalls;
        partial void OnmonitoringCallsChanging(global::System.String value);
        partial void OnmonitoringCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String multiSeconds
        {
            get
            {
                return _multiSeconds;
            }
            set
            {
                OnmultiSecondsChanging(value);
                ReportPropertyChanging("multiSeconds");
                _multiSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("multiSeconds");
                OnmultiSecondsChanged();
            }
        }
        private global::System.String _multiSeconds;
        partial void OnmultiSecondsChanging(global::System.String value);
        partial void OnmultiSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notReadySeconds
        {
            get
            {
                return _notReadySeconds;
            }
            set
            {
                OnnotReadySecondsChanging(value);
                ReportPropertyChanging("notReadySeconds");
                _notReadySeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notReadySeconds");
                OnnotReadySecondsChanged();
            }
        }
        private global::System.String _notReadySeconds;
        partial void OnnotReadySecondsChanging(global::System.String value);
        partial void OnnotReadySecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfCallbacks
        {
            get
            {
                return _numberOfCallbacks;
            }
            set
            {
                OnnumberOfCallbacksChanging(value);
                ReportPropertyChanging("numberOfCallbacks");
                _numberOfCallbacks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfCallbacks");
                OnnumberOfCallbacksChanged();
            }
        }
        private global::System.String _numberOfCallbacks;
        partial void OnnumberOfCallbacksChanging(global::System.String value);
        partial void OnnumberOfCallbacksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfRefusals
        {
            get
            {
                return _numberOfRefusals;
            }
            set
            {
                OnnumberOfRefusalsChanging(value);
                ReportPropertyChanging("numberOfRefusals");
                _numberOfRefusals = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfRefusals");
                OnnumberOfRefusalsChanged();
            }
        }
        private global::System.String _numberOfRefusals;
        partial void OnnumberOfRefusalsChanging(global::System.String value);
        partial void OnnumberOfRefusalsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfSuccesses
        {
            get
            {
                return _numberOfSuccesses;
            }
            set
            {
                OnnumberOfSuccessesChanging(value);
                ReportPropertyChanging("numberOfSuccesses");
                _numberOfSuccesses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfSuccesses");
                OnnumberOfSuccessesChanged();
            }
        }
        private global::System.String _numberOfSuccesses;
        partial void OnnumberOfSuccessesChanging(global::System.String value);
        partial void OnnumberOfSuccessesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String otherSeconds
        {
            get
            {
                return _otherSeconds;
            }
            set
            {
                OnotherSecondsChanging(value);
                ReportPropertyChanging("otherSeconds");
                _otherSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("otherSeconds");
                OnotherSecondsChanged();
            }
        }
        private global::System.String _otherSeconds;
        partial void OnotherSecondsChanging(global::System.String value);
        partial void OnotherSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String parkSeconds
        {
            get
            {
                return _parkSeconds;
            }
            set
            {
                OnparkSecondsChanging(value);
                ReportPropertyChanging("parkSeconds");
                _parkSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("parkSeconds");
                OnparkSecondsChanged();
            }
        }
        private global::System.String _parkSeconds;
        partial void OnparkSecondsChanging(global::System.String value);
        partial void OnparkSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String previewSeconds
        {
            get
            {
                return _previewSeconds;
            }
            set
            {
                OnpreviewSecondsChanging(value);
                ReportPropertyChanging("previewSeconds");
                _previewSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("previewSeconds");
                OnpreviewSecondsChanged();
            }
        }
        private global::System.String _previewSeconds;
        partial void OnpreviewSecondsChanging(global::System.String value);
        partial void OnpreviewSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rejectCalls
        {
            get
            {
                return _rejectCalls;
            }
            set
            {
                OnrejectCallsChanging(value);
                ReportPropertyChanging("rejectCalls");
                _rejectCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rejectCalls");
                OnrejectCallsChanged();
            }
        }
        private global::System.String _rejectCalls;
        partial void OnrejectCallsChanging(global::System.String value);
        partial void OnrejectCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedCalls
        {
            get
            {
                return _reservedCalls;
            }
            set
            {
                OnreservedCallsChanging(value);
                ReportPropertyChanging("reservedCalls");
                _reservedCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedCalls");
                OnreservedCallsChanged();
            }
        }
        private global::System.String _reservedCalls;
        partial void OnreservedCallsChanging(global::System.String value);
        partial void OnreservedCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedCallsReceived
        {
            get
            {
                return _reservedCallsReceived;
            }
            set
            {
                OnreservedCallsReceivedChanging(value);
                ReportPropertyChanging("reservedCallsReceived");
                _reservedCallsReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedCallsReceived");
                OnreservedCallsReceivedChanged();
            }
        }
        private global::System.String _reservedCallsReceived;
        partial void OnreservedCallsReceivedChanging(global::System.String value);
        partial void OnreservedCallsReceivedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedSeconds
        {
            get
            {
                return _reservedSeconds;
            }
            set
            {
                OnreservedSecondsChanging(value);
                ReportPropertyChanging("reservedSeconds");
                _reservedSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedSeconds");
                OnreservedSecondsChanged();
            }
        }
        private global::System.String _reservedSeconds;
        partial void OnreservedSecondsChanging(global::System.String value);
        partial void OnreservedSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedSecondsReceived
        {
            get
            {
                return _reservedSecondsReceived;
            }
            set
            {
                OnreservedSecondsReceivedChanging(value);
                ReportPropertyChanging("reservedSecondsReceived");
                _reservedSecondsReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedSecondsReceived");
                OnreservedSecondsReceivedChanged();
            }
        }
        private global::System.String _reservedSecondsReceived;
        partial void OnreservedSecondsReceivedChanging(global::System.String value);
        partial void OnreservedSecondsReceivedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String station
        {
            get
            {
                return _station;
            }
            set
            {
                OnstationChanging(value);
                ReportPropertyChanging("station");
                _station = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("station");
                OnstationChanged();
            }
        }
        private global::System.String _station;
        partial void OnstationChanging(global::System.String value);
        partial void OnstationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusReason
        {
            get
            {
                return _statusReason;
            }
            set
            {
                OnstatusReasonChanging(value);
                ReportPropertyChanging("statusReason");
                _statusReason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusReason");
                OnstatusReasonChanged();
            }
        }
        private global::System.String _statusReason;
        partial void OnstatusReasonChanging(global::System.String value);
        partial void OnstatusReasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusReasonId
        {
            get
            {
                return _statusReasonId;
            }
            set
            {
                OnstatusReasonIdChanging(value);
                ReportPropertyChanging("statusReasonId");
                _statusReasonId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusReasonId");
                OnstatusReasonIdChanged();
            }
        }
        private global::System.String _statusReasonId;
        partial void OnstatusReasonIdChanging(global::System.String value);
        partial void OnstatusReasonIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusSeconds
        {
            get
            {
                return _statusSeconds;
            }
            set
            {
                OnstatusSecondsChanging(value);
                ReportPropertyChanging("statusSeconds");
                _statusSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusSeconds");
                OnstatusSecondsChanged();
            }
        }
        private global::System.String _statusSeconds;
        partial void OnstatusSecondsChanging(global::System.String value);
        partial void OnstatusSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusStartTimeMilitary
        {
            get
            {
                return _statusStartTimeMilitary;
            }
            set
            {
                OnstatusStartTimeMilitaryChanging(value);
                ReportPropertyChanging("statusStartTimeMilitary");
                _statusStartTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusStartTimeMilitary");
                OnstatusStartTimeMilitaryChanged();
            }
        }
        private global::System.String _statusStartTimeMilitary;
        partial void OnstatusStartTimeMilitaryChanging(global::System.String value);
        partial void OnstatusStartTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferredCalls
        {
            get
            {
                return _transferredCalls;
            }
            set
            {
                OntransferredCallsChanging(value);
                ReportPropertyChanging("transferredCalls");
                _transferredCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferredCalls");
                OntransferredCallsChanged();
            }
        }
        private global::System.String _transferredCalls;
        partial void OntransferredCallsChanging(global::System.String value);
        partial void OntransferredCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String workgroup
        {
            get
            {
                return _workgroup;
            }
            set
            {
                OnworkgroupChanging(value);
                ReportPropertyChanging("workgroup");
                _workgroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("workgroup");
                OnworkgroupChanged();
            }
        }
        private global::System.String _workgroup;
        partial void OnworkgroupChanging(global::System.String value);
        partial void OnworkgroupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String workgroupId
        {
            get
            {
                return _workgroupId;
            }
            set
            {
                OnworkgroupIdChanging(value);
                ReportPropertyChanging("workgroupId");
                _workgroupId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("workgroupId");
                OnworkgroupIdChanged();
            }
        }
        private global::System.String _workgroupId;
        partial void OnworkgroupIdChanging(global::System.String value);
        partial void OnworkgroupIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wrapSeconds
        {
            get
            {
                return _wrapSeconds;
            }
            set
            {
                OnwrapSecondsChanging(value);
                ReportPropertyChanging("wrapSeconds");
                _wrapSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wrapSeconds");
                OnwrapSecondsChanged();
            }
        }
        private global::System.String _wrapSeconds;
        partial void OnwrapSecondsChanging(global::System.String value);
        partial void OnwrapSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contacts
        {
            get
            {
                return _contacts;
            }
            set
            {
                OncontactsChanging(value);
                ReportPropertyChanging("contacts");
                _contacts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contacts");
                OncontactsChanged();
            }
        }
        private global::System.String _contacts;
        partial void OncontactsChanging(global::System.String value);
        partial void OncontactsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String inactiveSeconds
        {
            get
            {
                return _inactiveSeconds;
            }
            set
            {
                OninactiveSecondsChanging(value);
                ReportPropertyChanging("inactiveSeconds");
                _inactiveSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("inactiveSeconds");
                OninactiveSecondsChanged();
            }
        }
        private global::System.String _inactiveSeconds;
        partial void OninactiveSecondsChanging(global::System.String value);
        partial void OninactiveSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneIdentifier
        {
            get
            {
                return _timezoneIdentifier;
            }
            set
            {
                OntimezoneIdentifierChanging(value);
                ReportPropertyChanging("timezoneIdentifier");
                _timezoneIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneIdentifier");
                OntimezoneIdentifierChanged();
            }
        }
        private global::System.String _timezoneIdentifier;
        partial void OntimezoneIdentifierChanging(global::System.String value);
        partial void OntimezoneIdentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStartTime
        {
            get
            {
                return _utcStartTime;
            }
            set
            {
                OnutcStartTimeChanging(value);
                ReportPropertyChanging("utcStartTime");
                _utcStartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStartTime");
                OnutcStartTimeChanged();
            }
        }
        private global::System.String _utcStartTime;
        partial void OnutcStartTimeChanging(global::System.String value);
        partial void OnutcStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application
        {
            get
            {
                return _application;
            }
            set
            {
                OnapplicationChanging(value);
                ReportPropertyChanging("application");
                _application = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application");
                OnapplicationChanged();
            }
        }
        private global::System.String _application;
        partial void OnapplicationChanging(global::System.String value);
        partial void OnapplicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.String _applicationId;
        partial void OnapplicationIdChanging(global::System.String value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timeArrival
        {
            get
            {
                return _timeArrival;
            }
            set
            {
                OntimeArrivalChanging(value);
                ReportPropertyChanging("timeArrival");
                _timeArrival = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timeArrival");
                OntimeArrivalChanged();
            }
        }
        private global::System.String _timeArrival;
        partial void OntimeArrivalChanging(global::System.String value);
        partial void OntimeArrivalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 primaryId
        {
            get
            {
                return _primaryId;
            }
            set
            {
                if (_primaryId != value)
                {
                    OnprimaryIdChanging(value);
                    ReportPropertyChanging("primaryId");
                    _primaryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("primaryId");
                    OnprimaryIdChanged();
                }
            }
        }
        private global::System.Int32 _primaryId;
        partial void OnprimaryIdChanging(global::System.Int32 value);
        partial void OnprimaryIdChanged();

        #endregion

    
    }

    #endregion

    
}
