//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities”部分中的连接字符串初始化新 testEntities 对象。
        /// </summary>
        public testEntities() : base("name=testEntities", "testEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities 对象。
        /// </summary>
        public testEntities(string connectionString) : base(connectionString, "testEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities 对象。
        /// </summary>
        public testEntities(EntityConnection connection) : base(connection, "testEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_aod> crm_aspect_monitor_aod
        {
            get
            {
                if ((_crm_aspect_monitor_aod == null))
                {
                    _crm_aspect_monitor_aod = base.CreateObjectSet<crm_aspect_monitor_aod>("crm_aspect_monitor_aod");
                }
                return _crm_aspect_monitor_aod;
            }
        }
        private ObjectSet<crm_aspect_monitor_aod> _crm_aspect_monitor_aod;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_aod EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_aod(crm_aspect_monitor_aod crm_aspect_monitor_aod)
        {
            base.AddObject("crm_aspect_monitor_aod", crm_aspect_monitor_aod);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="crm_aspect_monitor_aod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_aod : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_aod 对象。
        /// </summary>
        /// <param name="serviceid">serviceid 属性的初始值。</param>
        public static crm_aspect_monitor_aod Createcrm_aspect_monitor_aod(global::System.String serviceid)
        {
            crm_aspect_monitor_aod crm_aspect_monitor_aod = new crm_aspect_monitor_aod();
            crm_aspect_monitor_aod.serviceid = serviceid;
            return crm_aspect_monitor_aod;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serviceid
        {
            get
            {
                return _serviceid;
            }
            set
            {
                if (_serviceid != value)
                {
                    OnserviceidChanging(value);
                    ReportPropertyChanging("serviceid");
                    _serviceid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("serviceid");
                    OnserviceidChanged();
                }
            }
        }
        private global::System.String _serviceid;
        partial void OnserviceidChanging(global::System.String value);
        partial void OnserviceidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinaccept
        {
            get
            {
                return _agentsinaccept;
            }
            set
            {
                OnagentsinacceptChanging(value);
                ReportPropertyChanging("agentsinaccept");
                _agentsinaccept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinaccept");
                OnagentsinacceptChanged();
            }
        }
        private global::System.String _agentsinaccept;
        partial void OnagentsinacceptChanging(global::System.String value);
        partial void OnagentsinacceptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinactive
        {
            get
            {
                return _agentsinactive;
            }
            set
            {
                OnagentsinactiveChanging(value);
                ReportPropertyChanging("agentsinactive");
                _agentsinactive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinactive");
                OnagentsinactiveChanged();
            }
        }
        private global::System.String _agentsinactive;
        partial void OnagentsinactiveChanging(global::System.String value);
        partial void OnagentsinactiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinconnect
        {
            get
            {
                return _agentsinconnect;
            }
            set
            {
                OnagentsinconnectChanging(value);
                ReportPropertyChanging("agentsinconnect");
                _agentsinconnect = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinconnect");
                OnagentsinconnectChanged();
            }
        }
        private global::System.String _agentsinconnect;
        partial void OnagentsinconnectChanging(global::System.String value);
        partial void OnagentsinconnectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinhold
        {
            get
            {
                return _agentsinhold;
            }
            set
            {
                OnagentsinholdChanging(value);
                ReportPropertyChanging("agentsinhold");
                _agentsinhold = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinhold");
                OnagentsinholdChanged();
            }
        }
        private global::System.String _agentsinhold;
        partial void OnagentsinholdChanging(global::System.String value);
        partial void OnagentsinholdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinidle
        {
            get
            {
                return _agentsinidle;
            }
            set
            {
                OnagentsinidleChanging(value);
                ReportPropertyChanging("agentsinidle");
                _agentsinidle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinidle");
                OnagentsinidleChanged();
            }
        }
        private global::System.String _agentsinidle;
        partial void OnagentsinidleChanging(global::System.String value);
        partial void OnagentsinidleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsininternal
        {
            get
            {
                return _agentsininternal;
            }
            set
            {
                OnagentsininternalChanging(value);
                ReportPropertyChanging("agentsininternal");
                _agentsininternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsininternal");
                OnagentsininternalChanged();
            }
        }
        private global::System.String _agentsininternal;
        partial void OnagentsininternalChanging(global::System.String value);
        partial void OnagentsininternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinmanual
        {
            get
            {
                return _agentsinmanual;
            }
            set
            {
                OnagentsinmanualChanging(value);
                ReportPropertyChanging("agentsinmanual");
                _agentsinmanual = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinmanual");
                OnagentsinmanualChanged();
            }
        }
        private global::System.String _agentsinmanual;
        partial void OnagentsinmanualChanging(global::System.String value);
        partial void OnagentsinmanualChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinmultil
        {
            get
            {
                return _agentsinmultil;
            }
            set
            {
                OnagentsinmultilChanging(value);
                ReportPropertyChanging("agentsinmultil");
                _agentsinmultil = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinmultil");
                OnagentsinmultilChanged();
            }
        }
        private global::System.String _agentsinmultil;
        partial void OnagentsinmultilChanging(global::System.String value);
        partial void OnagentsinmultilChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinnotready
        {
            get
            {
                return _agentsinnotready;
            }
            set
            {
                OnagentsinnotreadyChanging(value);
                ReportPropertyChanging("agentsinnotready");
                _agentsinnotready = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinnotready");
                OnagentsinnotreadyChanged();
            }
        }
        private global::System.String _agentsinnotready;
        partial void OnagentsinnotreadyChanging(global::System.String value);
        partial void OnagentsinnotreadyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinother
        {
            get
            {
                return _agentsinother;
            }
            set
            {
                OnagentsinotherChanging(value);
                ReportPropertyChanging("agentsinother");
                _agentsinother = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinother");
                OnagentsinotherChanged();
            }
        }
        private global::System.String _agentsinother;
        partial void OnagentsinotherChanging(global::System.String value);
        partial void OnagentsinotherChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinpark
        {
            get
            {
                return _agentsinpark;
            }
            set
            {
                OnagentsinparkChanging(value);
                ReportPropertyChanging("agentsinpark");
                _agentsinpark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinpark");
                OnagentsinparkChanged();
            }
        }
        private global::System.String _agentsinpark;
        partial void OnagentsinparkChanging(global::System.String value);
        partial void OnagentsinparkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinpreview
        {
            get
            {
                return _agentsinpreview;
            }
            set
            {
                OnagentsinpreviewChanging(value);
                ReportPropertyChanging("agentsinpreview");
                _agentsinpreview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinpreview");
                OnagentsinpreviewChanged();
            }
        }
        private global::System.String _agentsinpreview;
        partial void OnagentsinpreviewChanging(global::System.String value);
        partial void OnagentsinpreviewChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsinwrap
        {
            get
            {
                return _agentsinwrap;
            }
            set
            {
                OnagentsinwrapChanging(value);
                ReportPropertyChanging("agentsinwrap");
                _agentsinwrap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsinwrap");
                OnagentsinwrapChanged();
            }
        }
        private global::System.String _agentsinwrap;
        partial void OnagentsinwrapChanging(global::System.String value);
        partial void OnagentsinwrapChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsloggedin
        {
            get
            {
                return _agentsloggedin;
            }
            set
            {
                OnagentsloggedinChanging(value);
                ReportPropertyChanging("agentsloggedin");
                _agentsloggedin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsloggedin");
                OnagentsloggedinChanged();
            }
        }
        private global::System.String _agentsloggedin;
        partial void OnagentsloggedinChanging(global::System.String value);
        partial void OnagentsloggedinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application
        {
            get
            {
                return _application;
            }
            set
            {
                OnapplicationChanging(value);
                ReportPropertyChanging("application");
                _application = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application");
                OnapplicationChanged();
            }
        }
        private global::System.String _application;
        partial void OnapplicationChanging(global::System.String value);
        partial void OnapplicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String applicationid
        {
            get
            {
                return _applicationid;
            }
            set
            {
                OnapplicationidChanging(value);
                ReportPropertyChanging("applicationid");
                _applicationid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("applicationid");
                OnapplicationidChanged();
            }
        }
        private global::System.String _applicationid;
        partial void OnapplicationidChanging(global::System.String value);
        partial void OnapplicationidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgagentactivetime
        {
            get
            {
                return _avgagentactivetime;
            }
            set
            {
                OnavgagentactivetimeChanging(value);
                ReportPropertyChanging("avgagentactivetime");
                _avgagentactivetime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgagentactivetime");
                OnavgagentactivetimeChanged();
            }
        }
        private global::System.String _avgagentactivetime;
        partial void OnavgagentactivetimeChanging(global::System.String value);
        partial void OnavgagentactivetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgagentidletime
        {
            get
            {
                return _avgagentidletime;
            }
            set
            {
                OnavgagentidletimeChanging(value);
                ReportPropertyChanging("avgagentidletime");
                _avgagentidletime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgagentidletime");
                OnavgagentidletimeChanged();
            }
        }
        private global::System.String _avgagentidletime;
        partial void OnavgagentidletimeChanging(global::System.String value);
        partial void OnavgagentidletimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgagentwraptime
        {
            get
            {
                return _avgagentwraptime;
            }
            set
            {
                OnavgagentwraptimeChanging(value);
                ReportPropertyChanging("avgagentwraptime");
                _avgagentwraptime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgagentwraptime");
                OnavgagentwraptimeChanged();
            }
        }
        private global::System.String _avgagentwraptime;
        partial void OnavgagentwraptimeChanging(global::System.String value);
        partial void OnavgagentwraptimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsanswered
        {
            get
            {
                return _callsanswered;
            }
            set
            {
                OncallsansweredChanging(value);
                ReportPropertyChanging("callsanswered");
                _callsanswered = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsanswered");
                OncallsansweredChanged();
            }
        }
        private global::System.String _callsanswered;
        partial void OncallsansweredChanging(global::System.String value);
        partial void OncallsansweredChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsinprogress
        {
            get
            {
                return _callsinprogress;
            }
            set
            {
                OncallsinprogressChanging(value);
                ReportPropertyChanging("callsinprogress");
                _callsinprogress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsinprogress");
                OncallsinprogressChanged();
            }
        }
        private global::System.String _callsinprogress;
        partial void OncallsinprogressChanging(global::System.String value);
        partial void OncallsinprogressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsinqueue
        {
            get
            {
                return _callsinqueue;
            }
            set
            {
                OncallsinqueueChanging(value);
                ReportPropertyChanging("callsinqueue");
                _callsinqueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsinqueue");
                OncallsinqueueChanged();
            }
        }
        private global::System.String _callsinqueue;
        partial void OncallsinqueueChanging(global::System.String value);
        partial void OncallsinqueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsservicedwithinserviceleveldaily
        {
            get
            {
                return _callsservicedwithinserviceleveldaily;
            }
            set
            {
                OncallsservicedwithinserviceleveldailyChanging(value);
                ReportPropertyChanging("callsservicedwithinserviceleveldaily");
                _callsservicedwithinserviceleveldaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsservicedwithinserviceleveldaily");
                OncallsservicedwithinserviceleveldailyChanged();
            }
        }
        private global::System.String _callsservicedwithinserviceleveldaily;
        partial void OncallsservicedwithinserviceleveldailyChanging(global::System.String value);
        partial void OncallsservicedwithinserviceleveldailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstransferredtoagent
        {
            get
            {
                return _callstransferredtoagent;
            }
            set
            {
                OncallstransferredtoagentChanging(value);
                ReportPropertyChanging("callstransferredtoagent");
                _callstransferredtoagent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstransferredtoagent");
                OncallstransferredtoagentChanged();
            }
        }
        private global::System.String _callstransferredtoagent;
        partial void OncallstransferredtoagentChanging(global::System.String value);
        partial void OncallstransferredtoagentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstransferredtoexternal
        {
            get
            {
                return _callstransferredtoexternal;
            }
            set
            {
                OncallstransferredtoexternalChanging(value);
                ReportPropertyChanging("callstransferredtoexternal");
                _callstransferredtoexternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstransferredtoexternal");
                OncallstransferredtoexternalChanged();
            }
        }
        private global::System.String _callstransferredtoexternal;
        partial void OncallstransferredtoexternalChanging(global::System.String value);
        partial void OncallstransferredtoexternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstransferredtoservice
        {
            get
            {
                return _callstransferredtoservice;
            }
            set
            {
                OncallstransferredtoserviceChanging(value);
                ReportPropertyChanging("callstransferredtoservice");
                _callstransferredtoservice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstransferredtoservice");
                OncallstransferredtoserviceChanged();
            }
        }
        private global::System.String _callstransferredtoservice;
        partial void OncallstransferredtoserviceChanging(global::System.String value);
        partial void OncallstransferredtoserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String duractivetime
        {
            get
            {
                return _duractivetime;
            }
            set
            {
                OnduractivetimeChanging(value);
                ReportPropertyChanging("duractivetime");
                _duractivetime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("duractivetime");
                OnduractivetimeChanged();
            }
        }
        private global::System.String _duractivetime;
        partial void OnduractivetimeChanging(global::System.String value);
        partial void OnduractivetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durwraptime
        {
            get
            {
                return _durwraptime;
            }
            set
            {
                OndurwraptimeChanging(value);
                ReportPropertyChanging("durwraptime");
                _durwraptime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durwraptime");
                OndurwraptimeChanged();
            }
        }
        private global::System.String _durwraptime;
        partial void OndurwraptimeChanging(global::System.String value);
        partial void OndurwraptimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxcallsinqueue
        {
            get
            {
                return _maxcallsinqueue;
            }
            set
            {
                OnmaxcallsinqueueChanging(value);
                ReportPropertyChanging("maxcallsinqueue");
                _maxcallsinqueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxcallsinqueue");
                OnmaxcallsinqueueChanged();
            }
        }
        private global::System.String _maxcallsinqueue;
        partial void OnmaxcallsinqueueChanging(global::System.String value);
        partial void OnmaxcallsinqueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String occupancy
        {
            get
            {
                return _occupancy;
            }
            set
            {
                OnoccupancyChanging(value);
                ReportPropertyChanging("occupancy");
                _occupancy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("occupancy");
                OnoccupancyChanged();
            }
        }
        private global::System.String _occupancy;
        partial void OnoccupancyChanging(global::System.String value);
        partial void OnoccupancyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String servicetype
        {
            get
            {
                return _servicetype;
            }
            set
            {
                OnservicetypeChanging(value);
                ReportPropertyChanging("servicetype");
                _servicetype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("servicetype");
                OnservicetypeChanged();
            }
        }
        private global::System.String _servicetype;
        partial void OnservicetypeChanging(global::System.String value);
        partial void OnservicetypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String servicetypeid
        {
            get
            {
                return _servicetypeid;
            }
            set
            {
                OnservicetypeidChanging(value);
                ReportPropertyChanging("servicetypeid");
                _servicetypeid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("servicetypeid");
                OnservicetypeidChanged();
            }
        }
        private global::System.String _servicetypeid;
        partial void OnservicetypeidChanging(global::System.String value);
        partial void OnservicetypeidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String starttimemilitary
        {
            get
            {
                return _starttimemilitary;
            }
            set
            {
                OnstarttimemilitaryChanging(value);
                ReportPropertyChanging("starttimemilitary");
                _starttimemilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("starttimemilitary");
                OnstarttimemilitaryChanged();
            }
        }
        private global::System.String _starttimemilitary;
        partial void OnstarttimemilitaryChanging(global::System.String value);
        partial void OnstarttimemilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusid
        {
            get
            {
                return _statusid;
            }
            set
            {
                OnstatusidChanging(value);
                ReportPropertyChanging("statusid");
                _statusid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusid");
                OnstatusidChanged();
            }
        }
        private global::System.String _statusid;
        partial void OnstatusidChanging(global::System.String value);
        partial void OnstatusidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stoptimemilitary
        {
            get
            {
                return _stoptimemilitary;
            }
            set
            {
                OnstoptimemilitaryChanging(value);
                ReportPropertyChanging("stoptimemilitary");
                _stoptimemilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stoptimemilitary");
                OnstoptimemilitaryChanged();
            }
        }
        private global::System.String _stoptimemilitary;
        partial void OnstoptimemilitaryChanging(global::System.String value);
        partial void OnstoptimemilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonbydialer24hour
        {
            get
            {
                return _abandonbydialer24hour;
            }
            set
            {
                Onabandonbydialer24hourChanging(value);
                ReportPropertyChanging("abandonbydialer24hour");
                _abandonbydialer24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonbydialer24hour");
                Onabandonbydialer24hourChanged();
            }
        }
        private global::System.String _abandonbydialer24hour;
        partial void Onabandonbydialer24hourChanging(global::System.String value);
        partial void Onabandonbydialer24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedbycustomer
        {
            get
            {
                return _abandonedbycustomer;
            }
            set
            {
                OnabandonedbycustomerChanging(value);
                ReportPropertyChanging("abandonedbycustomer");
                _abandonedbycustomer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedbycustomer");
                OnabandonedbycustomerChanged();
            }
        }
        private global::System.String _abandonedbycustomer;
        partial void OnabandonedbycustomerChanging(global::System.String value);
        partial void OnabandonedbycustomerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedbyswitch
        {
            get
            {
                return _abandonedbyswitch;
            }
            set
            {
                OnabandonedbyswitchChanging(value);
                ReportPropertyChanging("abandonedbyswitch");
                _abandonedbyswitch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedbyswitch");
                OnabandonedbyswitchChanged();
            }
        }
        private global::System.String _abandonedbyswitch;
        partial void OnabandonedbyswitchChanging(global::System.String value);
        partial void OnabandonedbyswitchChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentansweringmachines
        {
            get
            {
                return _agentansweringmachines;
            }
            set
            {
                OnagentansweringmachinesChanging(value);
                ReportPropertyChanging("agentansweringmachines");
                _agentansweringmachines = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentansweringmachines");
                OnagentansweringmachinesChanged();
            }
        }
        private global::System.String _agentansweringmachines;
        partial void OnagentansweringmachinesChanging(global::System.String value);
        partial void OnagentansweringmachinesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentansweringmachines24hour
        {
            get
            {
                return _agentansweringmachines24hour;
            }
            set
            {
                Onagentansweringmachines24hourChanging(value);
                ReportPropertyChanging("agentansweringmachines24hour");
                _agentansweringmachines24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentansweringmachines24hour");
                Onagentansweringmachines24hourChanged();
            }
        }
        private global::System.String _agentansweringmachines24hour;
        partial void Onagentansweringmachines24hourChanging(global::System.String value);
        partial void Onagentansweringmachines24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedpercent
        {
            get
            {
                return _abandonedpercent;
            }
            set
            {
                OnabandonedpercentChanging(value);
                ReportPropertyChanging("abandonedpercent");
                _abandonedpercent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedpercent");
                OnabandonedpercentChanged();
            }
        }
        private global::System.String _abandonedpercent;
        partial void OnabandonedpercentChanging(global::System.String value);
        partial void OnabandonedpercentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answeringmachines24hour
        {
            get
            {
                return _answeringmachines24hour;
            }
            set
            {
                Onansweringmachines24hourChanging(value);
                ReportPropertyChanging("answeringmachines24hour");
                _answeringmachines24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answeringmachines24hour");
                Onansweringmachines24hourChanged();
            }
        }
        private global::System.String _answeringmachines24hour;
        partial void Onansweringmachines24hourChanging(global::System.String value);
        partial void Onansweringmachines24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answeringmachinescurrent
        {
            get
            {
                return _answeringmachinescurrent;
            }
            set
            {
                OnansweringmachinescurrentChanging(value);
                ReportPropertyChanging("answeringmachinescurrent");
                _answeringmachinescurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answeringmachinescurrent");
                OnansweringmachinescurrentChanged();
            }
        }
        private global::System.String _answeringmachinescurrent;
        partial void OnansweringmachinescurrentChanging(global::System.String value);
        partial void OnansweringmachinescurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String busyhourcallrate
        {
            get
            {
                return _busyhourcallrate;
            }
            set
            {
                OnbusyhourcallrateChanging(value);
                ReportPropertyChanging("busyhourcallrate");
                _busyhourcallrate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("busyhourcallrate");
                OnbusyhourcallrateChanged();
            }
        }
        private global::System.String _busyhourcallrate;
        partial void OnbusyhourcallrateChanging(global::System.String value);
        partial void OnbusyhourcallrateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callingpartyinfoviolation
        {
            get
            {
                return _callingpartyinfoviolation;
            }
            set
            {
                OncallingpartyinfoviolationChanging(value);
                ReportPropertyChanging("callingpartyinfoviolation");
                _callingpartyinfoviolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callingpartyinfoviolation");
                OncallingpartyinfoviolationChanged();
            }
        }
        private global::System.String _callingpartyinfoviolation;
        partial void OncallingpartyinfoviolationChanging(global::System.String value);
        partial void OncallingpartyinfoviolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsansweredservicelevelinterval
        {
            get
            {
                return _callsansweredservicelevelinterval;
            }
            set
            {
                OncallsansweredservicelevelintervalChanging(value);
                ReportPropertyChanging("callsansweredservicelevelinterval");
                _callsansweredservicelevelinterval = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsansweredservicelevelinterval");
                OncallsansweredservicelevelintervalChanged();
            }
        }
        private global::System.String _callsansweredservicelevelinterval;
        partial void OncallsansweredservicelevelintervalChanging(global::System.String value);
        partial void OncallsansweredservicelevelintervalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsdialed
        {
            get
            {
                return _callsdialed;
            }
            set
            {
                OncallsdialedChanging(value);
                ReportPropertyChanging("callsdialed");
                _callsdialed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsdialed");
                OncallsdialedChanged();
            }
        }
        private global::System.String _callsdialed;
        partial void OncallsdialedChanging(global::System.String value);
        partial void OncallsdialedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstarttogreetingaverage
        {
            get
            {
                return _callstarttogreetingaverage;
            }
            set
            {
                OncallstarttogreetingaverageChanging(value);
                ReportPropertyChanging("callstarttogreetingaverage");
                _callstarttogreetingaverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstarttogreetingaverage");
                OncallstarttogreetingaverageChanged();
            }
        }
        private global::System.String _callstarttogreetingaverage;
        partial void OncallstarttogreetingaverageChanging(global::System.String value);
        partial void OncallstarttogreetingaverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstarttogreetinghigh
        {
            get
            {
                return _callstarttogreetinghigh;
            }
            set
            {
                OncallstarttogreetinghighChanging(value);
                ReportPropertyChanging("callstarttogreetinghigh");
                _callstarttogreetinghigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstarttogreetinghigh");
                OncallstarttogreetinghighChanged();
            }
        }
        private global::System.String _callstarttogreetinghigh;
        partial void OncallstarttogreetinghighChanging(global::System.String value);
        partial void OncallstarttogreetinghighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callstarttogreetinglow
        {
            get
            {
                return _callstarttogreetinglow;
            }
            set
            {
                OncallstarttogreetinglowChanging(value);
                ReportPropertyChanging("callstarttogreetinglow");
                _callstarttogreetinglow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callstarttogreetinglow");
                OncallstarttogreetinglowChanged();
            }
        }
        private global::System.String _callstarttogreetinglow;
        partial void OncallstarttogreetinglowChanging(global::System.String value);
        partial void OncallstarttogreetinglowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentdetectiontype
        {
            get
            {
                return _currentdetectiontype;
            }
            set
            {
                OncurrentdetectiontypeChanging(value);
                ReportPropertyChanging("currentdetectiontype");
                _currentdetectiontype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentdetectiontype");
                OncurrentdetectiontypeChanged();
            }
        }
        private global::System.String _currentdetectiontype;
        partial void OncurrentdetectiontypeChanging(global::System.String value);
        partial void OncurrentdetectiontypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentdialmode
        {
            get
            {
                return _currentdialmode;
            }
            set
            {
                OncurrentdialmodeChanging(value);
                ReportPropertyChanging("currentdialmode");
                _currentdialmode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentdialmode");
                OncurrentdialmodeChanged();
            }
        }
        private global::System.String _currentdialmode;
        partial void OncurrentdialmodeChanging(global::System.String value);
        partial void OncurrentdialmodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentdialratio
        {
            get
            {
                return _currentdialratio;
            }
            set
            {
                OncurrentdialratioChanging(value);
                ReportPropertyChanging("currentdialratio");
                _currentdialratio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentdialratio");
                OncurrentdialratioChanged();
            }
        }
        private global::System.String _currentdialratio;
        partial void OncurrentdialratioChanging(global::System.String value);
        partial void OncurrentdialratioChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentdialsettingsautorevert
        {
            get
            {
                return _currentdialsettingsautorevert;
            }
            set
            {
                OncurrentdialsettingsautorevertChanging(value);
                ReportPropertyChanging("currentdialsettingsautorevert");
                _currentdialsettingsautorevert = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentdialsettingsautorevert");
                OncurrentdialsettingsautorevertChanged();
            }
        }
        private global::System.String _currentdialsettingsautorevert;
        partial void OncurrentdialsettingsautorevertChanging(global::System.String value);
        partial void OncurrentdialsettingsautorevertChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentquota
        {
            get
            {
                return _currentquota;
            }
            set
            {
                OncurrentquotaChanging(value);
                ReportPropertyChanging("currentquota");
                _currentquota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentquota");
                OncurrentquotaChanged();
            }
        }
        private global::System.String _currentquota;
        partial void OncurrentquotaChanging(global::System.String value);
        partial void OncurrentquotaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detecttotransferaverage
        {
            get
            {
                return _detecttotransferaverage;
            }
            set
            {
                OndetecttotransferaverageChanging(value);
                ReportPropertyChanging("detecttotransferaverage");
                _detecttotransferaverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detecttotransferaverage");
                OndetecttotransferaverageChanged();
            }
        }
        private global::System.String _detecttotransferaverage;
        partial void OndetecttotransferaverageChanging(global::System.String value);
        partial void OndetecttotransferaverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detecttotransferhigh
        {
            get
            {
                return _detecttotransferhigh;
            }
            set
            {
                OndetecttotransferhighChanging(value);
                ReportPropertyChanging("detecttotransferhigh");
                _detecttotransferhigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detecttotransferhigh");
                OndetecttotransferhighChanged();
            }
        }
        private global::System.String _detecttotransferhigh;
        partial void OndetecttotransferhighChanging(global::System.String value);
        partial void OndetecttotransferhighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detecttotransferlow
        {
            get
            {
                return _detecttotransferlow;
            }
            set
            {
                OndetecttotransferlowChanging(value);
                ReportPropertyChanging("detecttotransferlow");
                _detecttotransferlow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detecttotransferlow");
                OndetecttotransferlowChanged();
            }
        }
        private global::System.String _detecttotransferlow;
        partial void OndetecttotransferlowChanging(global::System.String value);
        partial void OndetecttotransferlowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String falsenegativecount
        {
            get
            {
                return _falsenegativecount;
            }
            set
            {
                OnfalsenegativecountChanging(value);
                ReportPropertyChanging("falsenegativecount");
                _falsenegativecount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("falsenegativecount");
                OnfalsenegativecountChanged();
            }
        }
        private global::System.String _falsenegativecount;
        partial void OnfalsenegativecountChanging(global::System.String value);
        partial void OnfalsenegativecountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String falsepositivecount
        {
            get
            {
                return _falsepositivecount;
            }
            set
            {
                OnfalsepositivecountChanging(value);
                ReportPropertyChanging("falsepositivecount");
                _falsepositivecount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("falsepositivecount");
                OnfalsepositivecountChanged();
            }
        }
        private global::System.String _falsepositivecount;
        partial void OnfalsepositivecountChanging(global::System.String value);
        partial void OnfalsepositivecountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtoconnectaverage
        {
            get
            {
                return _greetingtoconnectaverage;
            }
            set
            {
                OngreetingtoconnectaverageChanging(value);
                ReportPropertyChanging("greetingtoconnectaverage");
                _greetingtoconnectaverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtoconnectaverage");
                OngreetingtoconnectaverageChanged();
            }
        }
        private global::System.String _greetingtoconnectaverage;
        partial void OngreetingtoconnectaverageChanging(global::System.String value);
        partial void OngreetingtoconnectaverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtoconnecthigh
        {
            get
            {
                return _greetingtoconnecthigh;
            }
            set
            {
                OngreetingtoconnecthighChanging(value);
                ReportPropertyChanging("greetingtoconnecthigh");
                _greetingtoconnecthigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtoconnecthigh");
                OngreetingtoconnecthighChanged();
            }
        }
        private global::System.String _greetingtoconnecthigh;
        partial void OngreetingtoconnecthighChanging(global::System.String value);
        partial void OngreetingtoconnecthighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtoconnectlow
        {
            get
            {
                return _greetingtoconnectlow;
            }
            set
            {
                OngreetingtoconnectlowChanging(value);
                ReportPropertyChanging("greetingtoconnectlow");
                _greetingtoconnectlow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtoconnectlow");
                OngreetingtoconnectlowChanged();
            }
        }
        private global::System.String _greetingtoconnectlow;
        partial void OngreetingtoconnectlowChanging(global::System.String value);
        partial void OngreetingtoconnectlowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtodetectaverage
        {
            get
            {
                return _greetingtodetectaverage;
            }
            set
            {
                OngreetingtodetectaverageChanging(value);
                ReportPropertyChanging("greetingtodetectaverage");
                _greetingtodetectaverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtodetectaverage");
                OngreetingtodetectaverageChanged();
            }
        }
        private global::System.String _greetingtodetectaverage;
        partial void OngreetingtodetectaverageChanging(global::System.String value);
        partial void OngreetingtodetectaverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtodetecthigh
        {
            get
            {
                return _greetingtodetecthigh;
            }
            set
            {
                OngreetingtodetecthighChanging(value);
                ReportPropertyChanging("greetingtodetecthigh");
                _greetingtodetecthigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtodetecthigh");
                OngreetingtodetecthighChanged();
            }
        }
        private global::System.String _greetingtodetecthigh;
        partial void OngreetingtodetecthighChanging(global::System.String value);
        partial void OngreetingtodetecthighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingtodetectlow
        {
            get
            {
                return _greetingtodetectlow;
            }
            set
            {
                OngreetingtodetectlowChanging(value);
                ReportPropertyChanging("greetingtodetectlow");
                _greetingtodetectlow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingtodetectlow");
                OngreetingtodetectlowChanged();
            }
        }
        private global::System.String _greetingtodetectlow;
        partial void OngreetingtodetectlowChanging(global::System.String value);
        partial void OngreetingtodetectlowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hangup
        {
            get
            {
                return _hangup;
            }
            set
            {
                OnhangupChanging(value);
                ReportPropertyChanging("hangup");
                _hangup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hangup");
                OnhangupChanged();
            }
        }
        private global::System.String _hangup;
        partial void OnhangupChanging(global::System.String value);
        partial void OnhangupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hitrate
        {
            get
            {
                return _hitrate;
            }
            set
            {
                OnhitrateChanging(value);
                ReportPropertyChanging("hitrate");
                _hitrate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hitrate");
                OnhitrateChanged();
            }
        }
        private global::System.String _hitrate;
        partial void OnhitrateChanging(global::System.String value);
        partial void OnhitrateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastfailabandonpercent
        {
            get
            {
                return _lastfailabandonpercent;
            }
            set
            {
                OnlastfailabandonpercentChanging(value);
                ReportPropertyChanging("lastfailabandonpercent");
                _lastfailabandonpercent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastfailabandonpercent");
                OnlastfailabandonpercentChanged();
            }
        }
        private global::System.String _lastfailabandonpercent;
        partial void OnlastfailabandonpercentChanging(global::System.String value);
        partial void OnlastfailabandonpercentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lasttimetofail
        {
            get
            {
                return _lasttimetofail;
            }
            set
            {
                OnlasttimetofailChanging(value);
                ReportPropertyChanging("lasttimetofail");
                _lasttimetofail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lasttimetofail");
                OnlasttimetofailChanged();
            }
        }
        private global::System.String _lasttimetofail;
        partial void OnlasttimetofailChanging(global::System.String value);
        partial void OnlasttimetofailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lasttimetorecover
        {
            get
            {
                return _lasttimetorecover;
            }
            set
            {
                OnlasttimetorecoverChanging(value);
                ReportPropertyChanging("lasttimetorecover");
                _lasttimetorecover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lasttimetorecover");
                OnlasttimetorecoverChanged();
            }
        }
        private global::System.String _lasttimetorecover;
        partial void OnlasttimetorecoverChanging(global::System.String value);
        partial void OnlasttimetorecoverChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxquota
        {
            get
            {
                return _maxquota;
            }
            set
            {
                OnmaxquotaChanging(value);
                ReportPropertyChanging("maxquota");
                _maxquota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxquota");
                OnmaxquotaChanged();
            }
        }
        private global::System.String _maxquota;
        partial void OnmaxquotaChanging(global::System.String value);
        partial void OnmaxquotaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String minutesleftonschedule
        {
            get
            {
                return _minutesleftonschedule;
            }
            set
            {
                OnminutesleftonscheduleChanging(value);
                ReportPropertyChanging("minutesleftonschedule");
                _minutesleftonschedule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("minutesleftonschedule");
                OnminutesleftonscheduleChanged();
            }
        }
        private global::System.String _minutesleftonschedule;
        partial void OnminutesleftonscheduleChanging(global::System.String value);
        partial void OnminutesleftonscheduleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberalertsofcom
        {
            get
            {
                return _numberalertsofcom;
            }
            set
            {
                OnnumberalertsofcomChanging(value);
                ReportPropertyChanging("numberalertsofcom");
                _numberalertsofcom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberalertsofcom");
                OnnumberalertsofcomChanged();
            }
        }
        private global::System.String _numberalertsofcom;
        partial void OnnumberalertsofcomChanging(global::System.String value);
        partial void OnnumberalertsofcomChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberalertsofcom24hours
        {
            get
            {
                return _numberalertsofcom24hours;
            }
            set
            {
                Onnumberalertsofcom24hoursChanging(value);
                ReportPropertyChanging("numberalertsofcom24hours");
                _numberalertsofcom24hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberalertsofcom24hours");
                Onnumberalertsofcom24hoursChanged();
            }
        }
        private global::System.String _numberalertsofcom24hours;
        partial void Onnumberalertsofcom24hoursChanging(global::System.String value);
        partial void Onnumberalertsofcom24hoursChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberhits24hour
        {
            get
            {
                return _numberhits24hour;
            }
            set
            {
                Onnumberhits24hourChanging(value);
                ReportPropertyChanging("numberhits24hour");
                _numberhits24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberhits24hour");
                Onnumberhits24hourChanged();
            }
        }
        private global::System.String _numberhits24hour;
        partial void Onnumberhits24hourChanging(global::System.String value);
        partial void Onnumberhits24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberhits24hourforfalsepositive
        {
            get
            {
                return _numberhits24hourforfalsepositive;
            }
            set
            {
                Onnumberhits24hourforfalsepositiveChanging(value);
                ReportPropertyChanging("numberhits24hourforfalsepositive");
                _numberhits24hourforfalsepositive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberhits24hourforfalsepositive");
                Onnumberhits24hourforfalsepositiveChanged();
            }
        }
        private global::System.String _numberhits24hourforfalsepositive;
        partial void Onnumberhits24hourforfalsepositiveChanging(global::System.String value);
        partial void Onnumberhits24hourforfalsepositiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberhitscurrent
        {
            get
            {
                return _numberhitscurrent;
            }
            set
            {
                OnnumberhitscurrentChanging(value);
                ReportPropertyChanging("numberhitscurrent");
                _numberhitscurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberhitscurrent");
                OnnumberhitscurrentChanged();
            }
        }
        private global::System.String _numberhitscurrent;
        partial void OnnumberhitscurrentChanging(global::System.String value);
        partial void OnnumberhitscurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberhitsforfalsepositivecurrent
        {
            get
            {
                return _numberhitsforfalsepositivecurrent;
            }
            set
            {
                OnnumberhitsforfalsepositivecurrentChanging(value);
                ReportPropertyChanging("numberhitsforfalsepositivecurrent");
                _numberhitsforfalsepositivecurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberhitsforfalsepositivecurrent");
                OnnumberhitsforfalsepositivecurrentChanged();
            }
        }
        private global::System.String _numberhitsforfalsepositivecurrent;
        partial void OnnumberhitsforfalsepositivecurrentChanging(global::System.String value);
        partial void OnnumberhitsforfalsepositivecurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numbermisses24hour
        {
            get
            {
                return _numbermisses24hour;
            }
            set
            {
                Onnumbermisses24hourChanging(value);
                ReportPropertyChanging("numbermisses24hour");
                _numbermisses24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numbermisses24hour");
                Onnumbermisses24hourChanged();
            }
        }
        private global::System.String _numbermisses24hour;
        partial void Onnumbermisses24hourChanging(global::System.String value);
        partial void Onnumbermisses24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numbermissescurrent
        {
            get
            {
                return _numbermissescurrent;
            }
            set
            {
                OnnumbermissescurrentChanging(value);
                ReportPropertyChanging("numbermissescurrent");
                _numbermissescurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numbermissescurrent");
                OnnumbermissescurrentChanged();
            }
        }
        private global::System.String _numbermissescurrent;
        partial void OnnumbermissescurrentChanging(global::System.String value);
        partial void OnnumbermissescurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberofcomabandons24hour
        {
            get
            {
                return _numberofcomabandons24hour;
            }
            set
            {
                Onnumberofcomabandons24hourChanging(value);
                ReportPropertyChanging("numberofcomabandons24hour");
                _numberofcomabandons24hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberofcomabandons24hour");
                Onnumberofcomabandons24hourChanged();
            }
        }
        private global::System.String _numberofcomabandons24hour;
        partial void Onnumberofcomabandons24hourChanging(global::System.String value);
        partial void Onnumberofcomabandons24hourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberofcomabandonscurrent
        {
            get
            {
                return _numberofcomabandonscurrent;
            }
            set
            {
                OnnumberofcomabandonscurrentChanging(value);
                ReportPropertyChanging("numberofcomabandonscurrent");
                _numberofcomabandonscurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberofcomabandonscurrent");
                OnnumberofcomabandonscurrentChanged();
            }
        }
        private global::System.String _numberofcomabandonscurrent;
        partial void OnnumberofcomabandonscurrentChanging(global::System.String value);
        partial void OnnumberofcomabandonscurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberofrecoveries
        {
            get
            {
                return _numberofrecoveries;
            }
            set
            {
                OnnumberofrecoveriesChanging(value);
                ReportPropertyChanging("numberofrecoveries");
                _numberofrecoveries = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberofrecoveries");
                OnnumberofrecoveriesChanged();
            }
        }
        private global::System.String _numberofrecoveries;
        partial void OnnumberofrecoveriesChanging(global::System.String value);
        partial void OnnumberofrecoveriesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberofsales
        {
            get
            {
                return _numberofsales;
            }
            set
            {
                OnnumberofsalesChanging(value);
                ReportPropertyChanging("numberofsales");
                _numberofsales = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberofsales");
                OnnumberofsalesChanged();
            }
        }
        private global::System.String _numberofsales;
        partial void OnnumberofsalesChanging(global::System.String value);
        partial void OnnumberofsalesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String peakhourcallrate
        {
            get
            {
                return _peakhourcallrate;
            }
            set
            {
                OnpeakhourcallrateChanging(value);
                ReportPropertyChanging("peakhourcallrate");
                _peakhourcallrate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("peakhourcallrate");
                OnpeakhourcallrateChanged();
            }
        }
        private global::System.String _peakhourcallrate;
        partial void OnpeakhourcallrateChanging(global::System.String value);
        partial void OnpeakhourcallrateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playmessage
        {
            get
            {
                return _playmessage;
            }
            set
            {
                OnplaymessageChanging(value);
                ReportPropertyChanging("playmessage");
                _playmessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playmessage");
                OnplaymessageChanged();
            }
        }
        private global::System.String _playmessage;
        partial void OnplaymessageChanging(global::System.String value);
        partial void OnplaymessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playmessagefailure
        {
            get
            {
                return _playmessagefailure;
            }
            set
            {
                OnplaymessagefailureChanging(value);
                ReportPropertyChanging("playmessagefailure");
                _playmessagefailure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playmessagefailure");
                OnplaymessagefailureChanged();
            }
        }
        private global::System.String _playmessagefailure;
        partial void OnplaymessagefailureChanging(global::System.String value);
        partial void OnplaymessagefailureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playmessagetimesuccess
        {
            get
            {
                return _playmessagetimesuccess;
            }
            set
            {
                OnplaymessagetimesuccessChanging(value);
                ReportPropertyChanging("playmessagetimesuccess");
                _playmessagetimesuccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playmessagetimesuccess");
                OnplaymessagetimesuccessChanged();
            }
        }
        private global::System.String _playmessagetimesuccess;
        partial void OnplaymessagetimesuccessChanging(global::System.String value);
        partial void OnplaymessagetimesuccessChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playmessagetimeviolation
        {
            get
            {
                return _playmessagetimeviolation;
            }
            set
            {
                OnplaymessagetimeviolationChanging(value);
                ReportPropertyChanging("playmessagetimeviolation");
                _playmessagetimeviolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playmessagetimeviolation");
                OnplaymessagetimeviolationChanged();
            }
        }
        private global::System.String _playmessagetimeviolation;
        partial void OnplaymessagetimeviolationChanging(global::System.String value);
        partial void OnplaymessagetimeviolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playscript
        {
            get
            {
                return _playscript;
            }
            set
            {
                OnplayscriptChanging(value);
                ReportPropertyChanging("playscript");
                _playscript = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playscript");
                OnplayscriptChanged();
            }
        }
        private global::System.String _playscript;
        partial void OnplayscriptChanging(global::System.String value);
        partial void OnplayscriptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recoverytimebegin
        {
            get
            {
                return _recoverytimebegin;
            }
            set
            {
                OnrecoverytimebeginChanging(value);
                ReportPropertyChanging("recoverytimebegin");
                _recoverytimebegin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recoverytimebegin");
                OnrecoverytimebeginChanged();
            }
        }
        private global::System.String _recoverytimebegin;
        partial void OnrecoverytimebeginChanging(global::System.String value);
        partial void OnrecoverytimebeginChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recoverytimeend
        {
            get
            {
                return _recoverytimeend;
            }
            set
            {
                OnrecoverytimeendChanging(value);
                ReportPropertyChanging("recoverytimeend");
                _recoverytimeend = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recoverytimeend");
                OnrecoverytimeendChanged();
            }
        }
        private global::System.String _recoverytimeend;
        partial void OnrecoverytimeendChanging(global::System.String value);
        partial void OnrecoverytimeendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ringnoanswerviolation
        {
            get
            {
                return _ringnoanswerviolation;
            }
            set
            {
                OnringnoanswerviolationChanging(value);
                ReportPropertyChanging("ringnoanswerviolation");
                _ringnoanswerviolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ringnoanswerviolation");
                OnringnoanswerviolationChanged();
            }
        }
        private global::System.String _ringnoanswerviolation;
        partial void OnringnoanswerviolationChanging(global::System.String value);
        partial void OnringnoanswerviolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String scheduledcallbacks
        {
            get
            {
                return _scheduledcallbacks;
            }
            set
            {
                OnscheduledcallbacksChanging(value);
                ReportPropertyChanging("scheduledcallbacks");
                _scheduledcallbacks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("scheduledcallbacks");
                OnscheduledcallbacksChanged();
            }
        }
        private global::System.String _scheduledcallbacks;
        partial void OnscheduledcallbacksChanging(global::System.String value);
        partial void OnscheduledcallbacksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String senddigits
        {
            get
            {
                return _senddigits;
            }
            set
            {
                OnsenddigitsChanging(value);
                ReportPropertyChanging("senddigits");
                _senddigits = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("senddigits");
                OnsenddigitsChanged();
            }
        }
        private global::System.String _senddigits;
        partial void OnsenddigitsChanging(global::System.String value);
        partial void OnsenddigitsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sendfax
        {
            get
            {
                return _sendfax;
            }
            set
            {
                OnsendfaxChanging(value);
                ReportPropertyChanging("sendfax");
                _sendfax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sendfax");
                OnsendfaxChanged();
            }
        }
        private global::System.String _sendfax;
        partial void OnsendfaxChanging(global::System.String value);
        partial void OnsendfaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneidentifier
        {
            get
            {
                return _timezoneidentifier;
            }
            set
            {
                OntimezoneidentifierChanging(value);
                ReportPropertyChanging("timezoneidentifier");
                _timezoneidentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneidentifier");
                OntimezoneidentifierChanged();
            }
        }
        private global::System.String _timezoneidentifier;
        partial void OntimezoneidentifierChanging(global::System.String value);
        partial void OntimezoneidentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfertimesuccess
        {
            get
            {
                return _transfertimesuccess;
            }
            set
            {
                OntransfertimesuccessChanging(value);
                ReportPropertyChanging("transfertimesuccess");
                _transfertimesuccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfertimesuccess");
                OntransfertimesuccessChanged();
            }
        }
        private global::System.String _transfertimesuccess;
        partial void OntransfertimesuccessChanging(global::System.String value);
        partial void OntransfertimesuccessChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfertimeviolation
        {
            get
            {
                return _transfertimeviolation;
            }
            set
            {
                OntransfertimeviolationChanging(value);
                ReportPropertyChanging("transfertimeviolation");
                _transfertimeviolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfertimeviolation");
                OntransfertimeviolationChanged();
            }
        }
        private global::System.String _transfertimeviolation;
        partial void OntransfertimeviolationChanging(global::System.String value);
        partial void OntransfertimeviolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfertoconnectaverage
        {
            get
            {
                return _transfertoconnectaverage;
            }
            set
            {
                OntransfertoconnectaverageChanging(value);
                ReportPropertyChanging("transfertoconnectaverage");
                _transfertoconnectaverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfertoconnectaverage");
                OntransfertoconnectaverageChanged();
            }
        }
        private global::System.String _transfertoconnectaverage;
        partial void OntransfertoconnectaverageChanging(global::System.String value);
        partial void OntransfertoconnectaverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfertoconnecthigh
        {
            get
            {
                return _transfertoconnecthigh;
            }
            set
            {
                OntransfertoconnecthighChanging(value);
                ReportPropertyChanging("transfertoconnecthigh");
                _transfertoconnecthigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfertoconnecthigh");
                OntransfertoconnecthighChanged();
            }
        }
        private global::System.String _transfertoconnecthigh;
        partial void OntransfertoconnecthighChanging(global::System.String value);
        partial void OntransfertoconnecthighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transfertoconnectlow
        {
            get
            {
                return _transfertoconnectlow;
            }
            set
            {
                OntransfertoconnectlowChanging(value);
                ReportPropertyChanging("transfertoconnectlow");
                _transfertoconnectlow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transfertoconnectlow");
                OntransfertoconnectlowChanged();
            }
        }
        private global::System.String _transfertoconnectlow;
        partial void OntransfertoconnectlowChanging(global::System.String value);
        partial void OntransfertoconnectlowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcstarttime
        {
            get
            {
                return _utcstarttime;
            }
            set
            {
                OnutcstarttimeChanging(value);
                ReportPropertyChanging("utcstarttime");
                _utcstarttime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcstarttime");
                OnutcstarttimeChanged();
            }
        }
        private global::System.String _utcstarttime;
        partial void OnutcstarttimeChanging(global::System.String value);
        partial void OnutcstarttimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcstoptime
        {
            get
            {
                return _utcstoptime;
            }
            set
            {
                OnutcstoptimeChanging(value);
                ReportPropertyChanging("utcstoptime");
                _utcstoptime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcstoptime");
                OnutcstoptimeChanged();
            }
        }
        private global::System.String _utcstoptime;
        partial void OnutcstoptimeChanging(global::System.String value);
        partial void OnutcstoptimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String getaoddata
        {
            get
            {
                return _getaoddata;
            }
            set
            {
                OngetaoddataChanging(value);
                ReportPropertyChanging("getaoddata");
                _getaoddata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("getaoddata");
                OngetaoddataChanged();
            }
        }
        private global::System.String _getaoddata;
        partial void OngetaoddataChanging(global::System.String value);
        partial void OngetaoddataChanged();

        #endregion

    
    }

    #endregion

    
}
