//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities2 : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities2”部分中的连接字符串初始化新 testEntities2 对象。
        /// </summary>
        public testEntities2() : base("name=testEntities2", "testEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities2 对象。
        /// </summary>
        public testEntities2(string connectionString) : base(connectionString, "testEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities2 对象。
        /// </summary>
        public testEntities2(EntityConnection connection) : base(connection, "testEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect> crm_aspect
        {
            get
            {
                if ((_crm_aspect == null))
                {
                    _crm_aspect = base.CreateObjectSet<crm_aspect>("crm_aspect");
                }
                return _crm_aspect;
            }
        }
        private ObjectSet<crm_aspect> _crm_aspect;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect(crm_aspect crm_aspect)
        {
            base.AddObject("crm_aspect", crm_aspect);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="crm_aspect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect 对象。
        /// </summary>
        /// <param name="serviceid">serviceid 属性的初始值。</param>
        public static crm_aspect Createcrm_aspect(global::System.String serviceid)
        {
            crm_aspect crm_aspect = new crm_aspect();
            crm_aspect.serviceid = serviceid;
            return crm_aspect;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serviceid
        {
            get
            {
                return _serviceid;
            }
            set
            {
                if (_serviceid != value)
                {
                    OnserviceidChanging(value);
                    ReportPropertyChanging("serviceid");
                    _serviceid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("serviceid");
                    OnserviceidChanged();
                }
            }
        }
        private global::System.String _serviceid;
        partial void OnserviceidChanging(global::System.String value);
        partial void OnserviceidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();

        #endregion

    
    }

    #endregion

    
}
