//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities”部分中的连接字符串初始化新 testEntities 对象。
        /// </summary>
        public testEntities() : base("name=testEntities", "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities 对象。
        /// </summary>
        public testEntities(string connectionString) : base(connectionString, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities 对象。
        /// </summary>
        public testEntities(EntityConnection connection) : base(connection, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_aod2> crm_aspect_monitor_aod2
        {
            get
            {
                if ((_crm_aspect_monitor_aod2 == null))
                {
                    _crm_aspect_monitor_aod2 = base.CreateObjectSet<crm_aspect_monitor_aod2>("crm_aspect_monitor_aod2");
                }
                return _crm_aspect_monitor_aod2;
            }
        }
        private ObjectSet<crm_aspect_monitor_aod2> _crm_aspect_monitor_aod2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_aod2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_aod2(crm_aspect_monitor_aod2 crm_aspect_monitor_aod2)
        {
            base.AddObject("crm_aspect_monitor_aod2", crm_aspect_monitor_aod2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="crm_aspect_monitor_aod2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_aod2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_aod2 对象。
        /// </summary>
        /// <param name="serviceid">serviceid 属性的初始值。</param>
        public static crm_aspect_monitor_aod2 Createcrm_aspect_monitor_aod2(global::System.String serviceid)
        {
            crm_aspect_monitor_aod2 crm_aspect_monitor_aod2 = new crm_aspect_monitor_aod2();
            crm_aspect_monitor_aod2.serviceid = serviceid;
            return crm_aspect_monitor_aod2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String serviceid
        {
            get
            {
                return _serviceid;
            }
            set
            {
                if (_serviceid != value)
                {
                    OnserviceidChanging(value);
                    ReportPropertyChanging("serviceid");
                    _serviceid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("serviceid");
                    OnserviceidChanged();
                }
            }
        }
        private global::System.String _serviceid;
        partial void OnserviceidChanging(global::System.String value);
        partial void OnserviceidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInAccept
        {
            get
            {
                return _agentsInAccept;
            }
            set
            {
                OnagentsInAcceptChanging(value);
                ReportPropertyChanging("agentsInAccept");
                _agentsInAccept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInAccept");
                OnagentsInAcceptChanged();
            }
        }
        private global::System.String _agentsInAccept;
        partial void OnagentsInAcceptChanging(global::System.String value);
        partial void OnagentsInAcceptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInActive
        {
            get
            {
                return _agentsInActive;
            }
            set
            {
                OnagentsInActiveChanging(value);
                ReportPropertyChanging("agentsInActive");
                _agentsInActive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInActive");
                OnagentsInActiveChanged();
            }
        }
        private global::System.String _agentsInActive;
        partial void OnagentsInActiveChanging(global::System.String value);
        partial void OnagentsInActiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInConnect
        {
            get
            {
                return _agentsInConnect;
            }
            set
            {
                OnagentsInConnectChanging(value);
                ReportPropertyChanging("agentsInConnect");
                _agentsInConnect = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInConnect");
                OnagentsInConnectChanged();
            }
        }
        private global::System.String _agentsInConnect;
        partial void OnagentsInConnectChanging(global::System.String value);
        partial void OnagentsInConnectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInHold
        {
            get
            {
                return _agentsInHold;
            }
            set
            {
                OnagentsInHoldChanging(value);
                ReportPropertyChanging("agentsInHold");
                _agentsInHold = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInHold");
                OnagentsInHoldChanged();
            }
        }
        private global::System.String _agentsInHold;
        partial void OnagentsInHoldChanging(global::System.String value);
        partial void OnagentsInHoldChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInHdle
        {
            get
            {
                return _agentsInHdle;
            }
            set
            {
                OnagentsInHdleChanging(value);
                ReportPropertyChanging("agentsInHdle");
                _agentsInHdle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInHdle");
                OnagentsInHdleChanged();
            }
        }
        private global::System.String _agentsInHdle;
        partial void OnagentsInHdleChanging(global::System.String value);
        partial void OnagentsInHdleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInInternal
        {
            get
            {
                return _agentsInInternal;
            }
            set
            {
                OnagentsInInternalChanging(value);
                ReportPropertyChanging("agentsInInternal");
                _agentsInInternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInInternal");
                OnagentsInInternalChanged();
            }
        }
        private global::System.String _agentsInInternal;
        partial void OnagentsInInternalChanging(global::System.String value);
        partial void OnagentsInInternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInManual
        {
            get
            {
                return _agentsInManual;
            }
            set
            {
                OnagentsInManualChanging(value);
                ReportPropertyChanging("agentsInManual");
                _agentsInManual = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInManual");
                OnagentsInManualChanged();
            }
        }
        private global::System.String _agentsInManual;
        partial void OnagentsInManualChanging(global::System.String value);
        partial void OnagentsInManualChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInMultil
        {
            get
            {
                return _agentsInMultil;
            }
            set
            {
                OnagentsInMultilChanging(value);
                ReportPropertyChanging("agentsInMultil");
                _agentsInMultil = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInMultil");
                OnagentsInMultilChanged();
            }
        }
        private global::System.String _agentsInMultil;
        partial void OnagentsInMultilChanging(global::System.String value);
        partial void OnagentsInMultilChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInNotReady
        {
            get
            {
                return _agentsInNotReady;
            }
            set
            {
                OnagentsInNotReadyChanging(value);
                ReportPropertyChanging("agentsInNotReady");
                _agentsInNotReady = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInNotReady");
                OnagentsInNotReadyChanged();
            }
        }
        private global::System.String _agentsInNotReady;
        partial void OnagentsInNotReadyChanging(global::System.String value);
        partial void OnagentsInNotReadyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInOther
        {
            get
            {
                return _agentsInOther;
            }
            set
            {
                OnagentsInOtherChanging(value);
                ReportPropertyChanging("agentsInOther");
                _agentsInOther = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInOther");
                OnagentsInOtherChanged();
            }
        }
        private global::System.String _agentsInOther;
        partial void OnagentsInOtherChanging(global::System.String value);
        partial void OnagentsInOtherChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInPark
        {
            get
            {
                return _agentsInPark;
            }
            set
            {
                OnagentsInParkChanging(value);
                ReportPropertyChanging("agentsInPark");
                _agentsInPark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInPark");
                OnagentsInParkChanged();
            }
        }
        private global::System.String _agentsInPark;
        partial void OnagentsInParkChanging(global::System.String value);
        partial void OnagentsInParkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInPreview
        {
            get
            {
                return _agentsInPreview;
            }
            set
            {
                OnagentsInPreviewChanging(value);
                ReportPropertyChanging("agentsInPreview");
                _agentsInPreview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInPreview");
                OnagentsInPreviewChanged();
            }
        }
        private global::System.String _agentsInPreview;
        partial void OnagentsInPreviewChanging(global::System.String value);
        partial void OnagentsInPreviewChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsInWrap
        {
            get
            {
                return _agentsInWrap;
            }
            set
            {
                OnagentsInWrapChanging(value);
                ReportPropertyChanging("agentsInWrap");
                _agentsInWrap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsInWrap");
                OnagentsInWrapChanged();
            }
        }
        private global::System.String _agentsInWrap;
        partial void OnagentsInWrapChanging(global::System.String value);
        partial void OnagentsInWrapChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentsLoggedIn
        {
            get
            {
                return _agentsLoggedIn;
            }
            set
            {
                OnagentsLoggedInChanging(value);
                ReportPropertyChanging("agentsLoggedIn");
                _agentsLoggedIn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentsLoggedIn");
                OnagentsLoggedInChanged();
            }
        }
        private global::System.String _agentsLoggedIn;
        partial void OnagentsLoggedInChanging(global::System.String value);
        partial void OnagentsLoggedInChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application
        {
            get
            {
                return _application;
            }
            set
            {
                OnapplicationChanging(value);
                ReportPropertyChanging("application");
                _application = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application");
                OnapplicationChanged();
            }
        }
        private global::System.String _application;
        partial void OnapplicationChanging(global::System.String value);
        partial void OnapplicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.String _applicationId;
        partial void OnapplicationIdChanging(global::System.String value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentActiveTime
        {
            get
            {
                return _avgAgentActiveTime;
            }
            set
            {
                OnavgAgentActiveTimeChanging(value);
                ReportPropertyChanging("avgAgentActiveTime");
                _avgAgentActiveTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentActiveTime");
                OnavgAgentActiveTimeChanged();
            }
        }
        private global::System.String _avgAgentActiveTime;
        partial void OnavgAgentActiveTimeChanging(global::System.String value);
        partial void OnavgAgentActiveTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentIdleTime
        {
            get
            {
                return _avgAgentIdleTime;
            }
            set
            {
                OnavgAgentIdleTimeChanging(value);
                ReportPropertyChanging("avgAgentIdleTime");
                _avgAgentIdleTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentIdleTime");
                OnavgAgentIdleTimeChanged();
            }
        }
        private global::System.String _avgAgentIdleTime;
        partial void OnavgAgentIdleTimeChanging(global::System.String value);
        partial void OnavgAgentIdleTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String avgAgentWrapTime
        {
            get
            {
                return _avgAgentWrapTime;
            }
            set
            {
                OnavgAgentWrapTimeChanging(value);
                ReportPropertyChanging("avgAgentWrapTime");
                _avgAgentWrapTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avgAgentWrapTime");
                OnavgAgentWrapTimeChanged();
            }
        }
        private global::System.String _avgAgentWrapTime;
        partial void OnavgAgentWrapTimeChanging(global::System.String value);
        partial void OnavgAgentWrapTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAnswered
        {
            get
            {
                return _callsAnswered;
            }
            set
            {
                OncallsAnsweredChanging(value);
                ReportPropertyChanging("callsAnswered");
                _callsAnswered = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAnswered");
                OncallsAnsweredChanged();
            }
        }
        private global::System.String _callsAnswered;
        partial void OncallsAnsweredChanging(global::System.String value);
        partial void OncallsAnsweredChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsInProgress
        {
            get
            {
                return _callsInProgress;
            }
            set
            {
                OncallsInProgressChanging(value);
                ReportPropertyChanging("callsInProgress");
                _callsInProgress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsInProgress");
                OncallsInProgressChanged();
            }
        }
        private global::System.String _callsInProgress;
        partial void OncallsInProgressChanging(global::System.String value);
        partial void OncallsInProgressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsInQueue
        {
            get
            {
                return _callsInQueue;
            }
            set
            {
                OncallsInQueueChanging(value);
                ReportPropertyChanging("callsInQueue");
                _callsInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsInQueue");
                OncallsInQueueChanged();
            }
        }
        private global::System.String _callsInQueue;
        partial void OncallsInQueueChanging(global::System.String value);
        partial void OncallsInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsServicedWithInServiceLevelDaily
        {
            get
            {
                return _callsServicedWithInServiceLevelDaily;
            }
            set
            {
                OncallsServicedWithInServiceLevelDailyChanging(value);
                ReportPropertyChanging("callsServicedWithInServiceLevelDaily");
                _callsServicedWithInServiceLevelDaily = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsServicedWithInServiceLevelDaily");
                OncallsServicedWithInServiceLevelDailyChanged();
            }
        }
        private global::System.String _callsServicedWithInServiceLevelDaily;
        partial void OncallsServicedWithInServiceLevelDailyChanging(global::System.String value);
        partial void OncallsServicedWithInServiceLevelDailyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToAgent
        {
            get
            {
                return _callsTransferredToAgent;
            }
            set
            {
                OncallsTransferredToAgentChanging(value);
                ReportPropertyChanging("callsTransferredToAgent");
                _callsTransferredToAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToAgent");
                OncallsTransferredToAgentChanged();
            }
        }
        private global::System.String _callsTransferredToAgent;
        partial void OncallsTransferredToAgentChanging(global::System.String value);
        partial void OncallsTransferredToAgentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToAxternal
        {
            get
            {
                return _callsTransferredToAxternal;
            }
            set
            {
                OncallsTransferredToAxternalChanging(value);
                ReportPropertyChanging("callsTransferredToAxternal");
                _callsTransferredToAxternal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToAxternal");
                OncallsTransferredToAxternalChanged();
            }
        }
        private global::System.String _callsTransferredToAxternal;
        partial void OncallsTransferredToAxternalChanging(global::System.String value);
        partial void OncallsTransferredToAxternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsTransferredToService
        {
            get
            {
                return _callsTransferredToService;
            }
            set
            {
                OncallsTransferredToServiceChanging(value);
                ReportPropertyChanging("callsTransferredToService");
                _callsTransferredToService = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsTransferredToService");
                OncallsTransferredToServiceChanged();
            }
        }
        private global::System.String _callsTransferredToService;
        partial void OncallsTransferredToServiceChanging(global::System.String value);
        partial void OncallsTransferredToServiceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durActiveTime
        {
            get
            {
                return _durActiveTime;
            }
            set
            {
                OndurActiveTimeChanging(value);
                ReportPropertyChanging("durActiveTime");
                _durActiveTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durActiveTime");
                OndurActiveTimeChanged();
            }
        }
        private global::System.String _durActiveTime;
        partial void OndurActiveTimeChanging(global::System.String value);
        partial void OndurActiveTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durWrapTime
        {
            get
            {
                return _durWrapTime;
            }
            set
            {
                OndurWrapTimeChanging(value);
                ReportPropertyChanging("durWrapTime");
                _durWrapTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durWrapTime");
                OndurWrapTimeChanged();
            }
        }
        private global::System.String _durWrapTime;
        partial void OndurWrapTimeChanging(global::System.String value);
        partial void OndurWrapTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxCallsInQueue
        {
            get
            {
                return _maxCallsInQueue;
            }
            set
            {
                OnmaxCallsInQueueChanging(value);
                ReportPropertyChanging("maxCallsInQueue");
                _maxCallsInQueue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxCallsInQueue");
                OnmaxCallsInQueueChanged();
            }
        }
        private global::System.String _maxCallsInQueue;
        partial void OnmaxCallsInQueueChanging(global::System.String value);
        partial void OnmaxCallsInQueueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String occupancy
        {
            get
            {
                return _occupancy;
            }
            set
            {
                OnoccupancyChanging(value);
                ReportPropertyChanging("occupancy");
                _occupancy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("occupancy");
                OnoccupancyChanged();
            }
        }
        private global::System.String _occupancy;
        partial void OnoccupancyChanging(global::System.String value);
        partial void OnoccupancyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceType
        {
            get
            {
                return _serviceType;
            }
            set
            {
                OnserviceTypeChanging(value);
                ReportPropertyChanging("serviceType");
                _serviceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceType");
                OnserviceTypeChanged();
            }
        }
        private global::System.String _serviceType;
        partial void OnserviceTypeChanging(global::System.String value);
        partial void OnserviceTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceTypeId
        {
            get
            {
                return _serviceTypeId;
            }
            set
            {
                OnserviceTypeIdChanging(value);
                ReportPropertyChanging("serviceTypeId");
                _serviceTypeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceTypeId");
                OnserviceTypeIdChanged();
            }
        }
        private global::System.String _serviceTypeId;
        partial void OnserviceTypeIdChanging(global::System.String value);
        partial void OnserviceTypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String startTimeMilitary
        {
            get
            {
                return _startTimeMilitary;
            }
            set
            {
                OnstartTimeMilitaryChanging(value);
                ReportPropertyChanging("startTimeMilitary");
                _startTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("startTimeMilitary");
                OnstartTimeMilitaryChanged();
            }
        }
        private global::System.String _startTimeMilitary;
        partial void OnstartTimeMilitaryChanging(global::System.String value);
        partial void OnstartTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.String _statusId;
        partial void OnstatusIdChanging(global::System.String value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stopTimeMilitary
        {
            get
            {
                return _stopTimeMilitary;
            }
            set
            {
                OnstopTimeMilitaryChanging(value);
                ReportPropertyChanging("stopTimeMilitary");
                _stopTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stopTimeMilitary");
                OnstopTimeMilitaryChanged();
            }
        }
        private global::System.String _stopTimeMilitary;
        partial void OnstopTimeMilitaryChanging(global::System.String value);
        partial void OnstopTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonByDialer24Hour
        {
            get
            {
                return _abandonByDialer24Hour;
            }
            set
            {
                OnabandonByDialer24HourChanging(value);
                ReportPropertyChanging("abandonByDialer24Hour");
                _abandonByDialer24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonByDialer24Hour");
                OnabandonByDialer24HourChanged();
            }
        }
        private global::System.String _abandonByDialer24Hour;
        partial void OnabandonByDialer24HourChanging(global::System.String value);
        partial void OnabandonByDialer24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedByCustomer
        {
            get
            {
                return _abandonedByCustomer;
            }
            set
            {
                OnabandonedByCustomerChanging(value);
                ReportPropertyChanging("abandonedByCustomer");
                _abandonedByCustomer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedByCustomer");
                OnabandonedByCustomerChanged();
            }
        }
        private global::System.String _abandonedByCustomer;
        partial void OnabandonedByCustomerChanging(global::System.String value);
        partial void OnabandonedByCustomerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedBySwitch
        {
            get
            {
                return _abandonedBySwitch;
            }
            set
            {
                OnabandonedBySwitchChanging(value);
                ReportPropertyChanging("abandonedBySwitch");
                _abandonedBySwitch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedBySwitch");
                OnabandonedBySwitchChanged();
            }
        }
        private global::System.String _abandonedBySwitch;
        partial void OnabandonedBySwitchChanging(global::System.String value);
        partial void OnabandonedBySwitchChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentAnsweringMachines
        {
            get
            {
                return _agentAnsweringMachines;
            }
            set
            {
                OnagentAnsweringMachinesChanging(value);
                ReportPropertyChanging("agentAnsweringMachines");
                _agentAnsweringMachines = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentAnsweringMachines");
                OnagentAnsweringMachinesChanged();
            }
        }
        private global::System.String _agentAnsweringMachines;
        partial void OnagentAnsweringMachinesChanging(global::System.String value);
        partial void OnagentAnsweringMachinesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agentAnsweringMachines24Hour
        {
            get
            {
                return _agentAnsweringMachines24Hour;
            }
            set
            {
                OnagentAnsweringMachines24HourChanging(value);
                ReportPropertyChanging("agentAnsweringMachines24Hour");
                _agentAnsweringMachines24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agentAnsweringMachines24Hour");
                OnagentAnsweringMachines24HourChanged();
            }
        }
        private global::System.String _agentAnsweringMachines24Hour;
        partial void OnagentAnsweringMachines24HourChanging(global::System.String value);
        partial void OnagentAnsweringMachines24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandonedPercent
        {
            get
            {
                return _abandonedPercent;
            }
            set
            {
                OnabandonedPercentChanging(value);
                ReportPropertyChanging("abandonedPercent");
                _abandonedPercent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandonedPercent");
                OnabandonedPercentChanged();
            }
        }
        private global::System.String _abandonedPercent;
        partial void OnabandonedPercentChanging(global::System.String value);
        partial void OnabandonedPercentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answeringMachines24Hour
        {
            get
            {
                return _answeringMachines24Hour;
            }
            set
            {
                OnansweringMachines24HourChanging(value);
                ReportPropertyChanging("answeringMachines24Hour");
                _answeringMachines24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answeringMachines24Hour");
                OnansweringMachines24HourChanged();
            }
        }
        private global::System.String _answeringMachines24Hour;
        partial void OnansweringMachines24HourChanging(global::System.String value);
        partial void OnansweringMachines24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answeringMachinesCurrent
        {
            get
            {
                return _answeringMachinesCurrent;
            }
            set
            {
                OnansweringMachinesCurrentChanging(value);
                ReportPropertyChanging("answeringMachinesCurrent");
                _answeringMachinesCurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answeringMachinesCurrent");
                OnansweringMachinesCurrentChanged();
            }
        }
        private global::System.String _answeringMachinesCurrent;
        partial void OnansweringMachinesCurrentChanging(global::System.String value);
        partial void OnansweringMachinesCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String busyHourCallRate
        {
            get
            {
                return _busyHourCallRate;
            }
            set
            {
                OnbusyHourCallRateChanging(value);
                ReportPropertyChanging("busyHourCallRate");
                _busyHourCallRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("busyHourCallRate");
                OnbusyHourCallRateChanged();
            }
        }
        private global::System.String _busyHourCallRate;
        partial void OnbusyHourCallRateChanging(global::System.String value);
        partial void OnbusyHourCallRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callingPartyInfoViolation
        {
            get
            {
                return _callingPartyInfoViolation;
            }
            set
            {
                OncallingPartyInfoViolationChanging(value);
                ReportPropertyChanging("callingPartyInfoViolation");
                _callingPartyInfoViolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callingPartyInfoViolation");
                OncallingPartyInfoViolationChanged();
            }
        }
        private global::System.String _callingPartyInfoViolation;
        partial void OncallingPartyInfoViolationChanging(global::System.String value);
        partial void OncallingPartyInfoViolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsAnsweredServiceLevelInterval
        {
            get
            {
                return _callsAnsweredServiceLevelInterval;
            }
            set
            {
                OncallsAnsweredServiceLevelIntervalChanging(value);
                ReportPropertyChanging("callsAnsweredServiceLevelInterval");
                _callsAnsweredServiceLevelInterval = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsAnsweredServiceLevelInterval");
                OncallsAnsweredServiceLevelIntervalChanged();
            }
        }
        private global::System.String _callsAnsweredServiceLevelInterval;
        partial void OncallsAnsweredServiceLevelIntervalChanging(global::System.String value);
        partial void OncallsAnsweredServiceLevelIntervalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callsDialed
        {
            get
            {
                return _callsDialed;
            }
            set
            {
                OncallsDialedChanging(value);
                ReportPropertyChanging("callsDialed");
                _callsDialed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callsDialed");
                OncallsDialedChanged();
            }
        }
        private global::System.String _callsDialed;
        partial void OncallsDialedChanging(global::System.String value);
        partial void OncallsDialedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callStartToGreetingAverage
        {
            get
            {
                return _callStartToGreetingAverage;
            }
            set
            {
                OncallStartToGreetingAverageChanging(value);
                ReportPropertyChanging("callStartToGreetingAverage");
                _callStartToGreetingAverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callStartToGreetingAverage");
                OncallStartToGreetingAverageChanged();
            }
        }
        private global::System.String _callStartToGreetingAverage;
        partial void OncallStartToGreetingAverageChanging(global::System.String value);
        partial void OncallStartToGreetingAverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callStartToGreetingHigh
        {
            get
            {
                return _callStartToGreetingHigh;
            }
            set
            {
                OncallStartToGreetingHighChanging(value);
                ReportPropertyChanging("callStartToGreetingHigh");
                _callStartToGreetingHigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callStartToGreetingHigh");
                OncallStartToGreetingHighChanged();
            }
        }
        private global::System.String _callStartToGreetingHigh;
        partial void OncallStartToGreetingHighChanging(global::System.String value);
        partial void OncallStartToGreetingHighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callStartToGreetingLow
        {
            get
            {
                return _callStartToGreetingLow;
            }
            set
            {
                OncallStartToGreetingLowChanging(value);
                ReportPropertyChanging("callStartToGreetingLow");
                _callStartToGreetingLow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callStartToGreetingLow");
                OncallStartToGreetingLowChanged();
            }
        }
        private global::System.String _callStartToGreetingLow;
        partial void OncallStartToGreetingLowChanging(global::System.String value);
        partial void OncallStartToGreetingLowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentDetectionType
        {
            get
            {
                return _currentDetectionType;
            }
            set
            {
                OncurrentDetectionTypeChanging(value);
                ReportPropertyChanging("currentDetectionType");
                _currentDetectionType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentDetectionType");
                OncurrentDetectionTypeChanged();
            }
        }
        private global::System.String _currentDetectionType;
        partial void OncurrentDetectionTypeChanging(global::System.String value);
        partial void OncurrentDetectionTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentDialMode
        {
            get
            {
                return _currentDialMode;
            }
            set
            {
                OncurrentDialModeChanging(value);
                ReportPropertyChanging("currentDialMode");
                _currentDialMode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentDialMode");
                OncurrentDialModeChanged();
            }
        }
        private global::System.String _currentDialMode;
        partial void OncurrentDialModeChanging(global::System.String value);
        partial void OncurrentDialModeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentDialRatio
        {
            get
            {
                return _currentDialRatio;
            }
            set
            {
                OncurrentDialRatioChanging(value);
                ReportPropertyChanging("currentDialRatio");
                _currentDialRatio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentDialRatio");
                OncurrentDialRatioChanged();
            }
        }
        private global::System.String _currentDialRatio;
        partial void OncurrentDialRatioChanging(global::System.String value);
        partial void OncurrentDialRatioChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentDialSettingsAutoRevert
        {
            get
            {
                return _currentDialSettingsAutoRevert;
            }
            set
            {
                OncurrentDialSettingsAutoRevertChanging(value);
                ReportPropertyChanging("currentDialSettingsAutoRevert");
                _currentDialSettingsAutoRevert = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentDialSettingsAutoRevert");
                OncurrentDialSettingsAutoRevertChanged();
            }
        }
        private global::System.String _currentDialSettingsAutoRevert;
        partial void OncurrentDialSettingsAutoRevertChanging(global::System.String value);
        partial void OncurrentDialSettingsAutoRevertChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentQuota
        {
            get
            {
                return _currentQuota;
            }
            set
            {
                OncurrentQuotaChanging(value);
                ReportPropertyChanging("currentQuota");
                _currentQuota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentQuota");
                OncurrentQuotaChanged();
            }
        }
        private global::System.String _currentQuota;
        partial void OncurrentQuotaChanging(global::System.String value);
        partial void OncurrentQuotaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detectToTransferAverage
        {
            get
            {
                return _detectToTransferAverage;
            }
            set
            {
                OndetectToTransferAverageChanging(value);
                ReportPropertyChanging("detectToTransferAverage");
                _detectToTransferAverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detectToTransferAverage");
                OndetectToTransferAverageChanged();
            }
        }
        private global::System.String _detectToTransferAverage;
        partial void OndetectToTransferAverageChanging(global::System.String value);
        partial void OndetectToTransferAverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detectToTransferHigh
        {
            get
            {
                return _detectToTransferHigh;
            }
            set
            {
                OndetectToTransferHighChanging(value);
                ReportPropertyChanging("detectToTransferHigh");
                _detectToTransferHigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detectToTransferHigh");
                OndetectToTransferHighChanged();
            }
        }
        private global::System.String _detectToTransferHigh;
        partial void OndetectToTransferHighChanging(global::System.String value);
        partial void OndetectToTransferHighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detectToTransferLow
        {
            get
            {
                return _detectToTransferLow;
            }
            set
            {
                OndetectToTransferLowChanging(value);
                ReportPropertyChanging("detectToTransferLow");
                _detectToTransferLow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detectToTransferLow");
                OndetectToTransferLowChanged();
            }
        }
        private global::System.String _detectToTransferLow;
        partial void OndetectToTransferLowChanging(global::System.String value);
        partial void OndetectToTransferLowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String falseNegativeCount
        {
            get
            {
                return _falseNegativeCount;
            }
            set
            {
                OnfalseNegativeCountChanging(value);
                ReportPropertyChanging("falseNegativeCount");
                _falseNegativeCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("falseNegativeCount");
                OnfalseNegativeCountChanged();
            }
        }
        private global::System.String _falseNegativeCount;
        partial void OnfalseNegativeCountChanging(global::System.String value);
        partial void OnfalseNegativeCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String falsePositiveCount
        {
            get
            {
                return _falsePositiveCount;
            }
            set
            {
                OnfalsePositiveCountChanging(value);
                ReportPropertyChanging("falsePositiveCount");
                _falsePositiveCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("falsePositiveCount");
                OnfalsePositiveCountChanged();
            }
        }
        private global::System.String _falsePositiveCount;
        partial void OnfalsePositiveCountChanging(global::System.String value);
        partial void OnfalsePositiveCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingToConnectAverage
        {
            get
            {
                return _greetingToConnectAverage;
            }
            set
            {
                OngreetingToConnectAverageChanging(value);
                ReportPropertyChanging("greetingToConnectAverage");
                _greetingToConnectAverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingToConnectAverage");
                OngreetingToConnectAverageChanged();
            }
        }
        private global::System.String _greetingToConnectAverage;
        partial void OngreetingToConnectAverageChanging(global::System.String value);
        partial void OngreetingToConnectAverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingToconnectHigh
        {
            get
            {
                return _greetingToconnectHigh;
            }
            set
            {
                OngreetingToconnectHighChanging(value);
                ReportPropertyChanging("greetingToconnectHigh");
                _greetingToconnectHigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingToconnectHigh");
                OngreetingToconnectHighChanged();
            }
        }
        private global::System.String _greetingToconnectHigh;
        partial void OngreetingToconnectHighChanging(global::System.String value);
        partial void OngreetingToconnectHighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingToconnectLow
        {
            get
            {
                return _greetingToconnectLow;
            }
            set
            {
                OngreetingToconnectLowChanging(value);
                ReportPropertyChanging("greetingToconnectLow");
                _greetingToconnectLow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingToconnectLow");
                OngreetingToconnectLowChanged();
            }
        }
        private global::System.String _greetingToconnectLow;
        partial void OngreetingToconnectLowChanging(global::System.String value);
        partial void OngreetingToconnectLowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingTodetectAverage
        {
            get
            {
                return _greetingTodetectAverage;
            }
            set
            {
                OngreetingTodetectAverageChanging(value);
                ReportPropertyChanging("greetingTodetectAverage");
                _greetingTodetectAverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingTodetectAverage");
                OngreetingTodetectAverageChanged();
            }
        }
        private global::System.String _greetingTodetectAverage;
        partial void OngreetingTodetectAverageChanging(global::System.String value);
        partial void OngreetingTodetectAverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingTodetectHigh
        {
            get
            {
                return _greetingTodetectHigh;
            }
            set
            {
                OngreetingTodetectHighChanging(value);
                ReportPropertyChanging("greetingTodetectHigh");
                _greetingTodetectHigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingTodetectHigh");
                OngreetingTodetectHighChanged();
            }
        }
        private global::System.String _greetingTodetectHigh;
        partial void OngreetingTodetectHighChanging(global::System.String value);
        partial void OngreetingTodetectHighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String greetingTodetectLow
        {
            get
            {
                return _greetingTodetectLow;
            }
            set
            {
                OngreetingTodetectLowChanging(value);
                ReportPropertyChanging("greetingTodetectLow");
                _greetingTodetectLow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("greetingTodetectLow");
                OngreetingTodetectLowChanged();
            }
        }
        private global::System.String _greetingTodetectLow;
        partial void OngreetingTodetectLowChanging(global::System.String value);
        partial void OngreetingTodetectLowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hangup
        {
            get
            {
                return _hangup;
            }
            set
            {
                OnhangupChanging(value);
                ReportPropertyChanging("hangup");
                _hangup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hangup");
                OnhangupChanged();
            }
        }
        private global::System.String _hangup;
        partial void OnhangupChanging(global::System.String value);
        partial void OnhangupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hitRate
        {
            get
            {
                return _hitRate;
            }
            set
            {
                OnhitRateChanging(value);
                ReportPropertyChanging("hitRate");
                _hitRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hitRate");
                OnhitRateChanged();
            }
        }
        private global::System.String _hitRate;
        partial void OnhitRateChanging(global::System.String value);
        partial void OnhitRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastFailAbandonPercent
        {
            get
            {
                return _lastFailAbandonPercent;
            }
            set
            {
                OnlastFailAbandonPercentChanging(value);
                ReportPropertyChanging("lastFailAbandonPercent");
                _lastFailAbandonPercent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastFailAbandonPercent");
                OnlastFailAbandonPercentChanged();
            }
        }
        private global::System.String _lastFailAbandonPercent;
        partial void OnlastFailAbandonPercentChanging(global::System.String value);
        partial void OnlastFailAbandonPercentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastTimeToFail
        {
            get
            {
                return _lastTimeToFail;
            }
            set
            {
                OnlastTimeToFailChanging(value);
                ReportPropertyChanging("lastTimeToFail");
                _lastTimeToFail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastTimeToFail");
                OnlastTimeToFailChanged();
            }
        }
        private global::System.String _lastTimeToFail;
        partial void OnlastTimeToFailChanging(global::System.String value);
        partial void OnlastTimeToFailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastTimeToRecover
        {
            get
            {
                return _lastTimeToRecover;
            }
            set
            {
                OnlastTimeToRecoverChanging(value);
                ReportPropertyChanging("lastTimeToRecover");
                _lastTimeToRecover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastTimeToRecover");
                OnlastTimeToRecoverChanged();
            }
        }
        private global::System.String _lastTimeToRecover;
        partial void OnlastTimeToRecoverChanging(global::System.String value);
        partial void OnlastTimeToRecoverChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String maxQuota
        {
            get
            {
                return _maxQuota;
            }
            set
            {
                OnmaxQuotaChanging(value);
                ReportPropertyChanging("maxQuota");
                _maxQuota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("maxQuota");
                OnmaxQuotaChanged();
            }
        }
        private global::System.String _maxQuota;
        partial void OnmaxQuotaChanging(global::System.String value);
        partial void OnmaxQuotaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String minutesLeftOnSchedule
        {
            get
            {
                return _minutesLeftOnSchedule;
            }
            set
            {
                OnminutesLeftOnScheduleChanging(value);
                ReportPropertyChanging("minutesLeftOnSchedule");
                _minutesLeftOnSchedule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("minutesLeftOnSchedule");
                OnminutesLeftOnScheduleChanged();
            }
        }
        private global::System.String _minutesLeftOnSchedule;
        partial void OnminutesLeftOnScheduleChanging(global::System.String value);
        partial void OnminutesLeftOnScheduleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberAlertsOFCOM
        {
            get
            {
                return _numberAlertsOFCOM;
            }
            set
            {
                OnnumberAlertsOFCOMChanging(value);
                ReportPropertyChanging("numberAlertsOFCOM");
                _numberAlertsOFCOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberAlertsOFCOM");
                OnnumberAlertsOFCOMChanged();
            }
        }
        private global::System.String _numberAlertsOFCOM;
        partial void OnnumberAlertsOFCOMChanging(global::System.String value);
        partial void OnnumberAlertsOFCOMChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberAlertsOFCOM24Hours
        {
            get
            {
                return _numberAlertsOFCOM24Hours;
            }
            set
            {
                OnnumberAlertsOFCOM24HoursChanging(value);
                ReportPropertyChanging("numberAlertsOFCOM24Hours");
                _numberAlertsOFCOM24Hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberAlertsOFCOM24Hours");
                OnnumberAlertsOFCOM24HoursChanged();
            }
        }
        private global::System.String _numberAlertsOFCOM24Hours;
        partial void OnnumberAlertsOFCOM24HoursChanging(global::System.String value);
        partial void OnnumberAlertsOFCOM24HoursChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberHits24Hour
        {
            get
            {
                return _numberHits24Hour;
            }
            set
            {
                OnnumberHits24HourChanging(value);
                ReportPropertyChanging("numberHits24Hour");
                _numberHits24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberHits24Hour");
                OnnumberHits24HourChanged();
            }
        }
        private global::System.String _numberHits24Hour;
        partial void OnnumberHits24HourChanging(global::System.String value);
        partial void OnnumberHits24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberHits24HourForFalsePositive
        {
            get
            {
                return _numberHits24HourForFalsePositive;
            }
            set
            {
                OnnumberHits24HourForFalsePositiveChanging(value);
                ReportPropertyChanging("numberHits24HourForFalsePositive");
                _numberHits24HourForFalsePositive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberHits24HourForFalsePositive");
                OnnumberHits24HourForFalsePositiveChanged();
            }
        }
        private global::System.String _numberHits24HourForFalsePositive;
        partial void OnnumberHits24HourForFalsePositiveChanging(global::System.String value);
        partial void OnnumberHits24HourForFalsePositiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberHitsCurrent
        {
            get
            {
                return _numberHitsCurrent;
            }
            set
            {
                OnnumberHitsCurrentChanging(value);
                ReportPropertyChanging("numberHitsCurrent");
                _numberHitsCurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberHitsCurrent");
                OnnumberHitsCurrentChanged();
            }
        }
        private global::System.String _numberHitsCurrent;
        partial void OnnumberHitsCurrentChanging(global::System.String value);
        partial void OnnumberHitsCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberHitsForFalsePositiveCurrent
        {
            get
            {
                return _numberHitsForFalsePositiveCurrent;
            }
            set
            {
                OnnumberHitsForFalsePositiveCurrentChanging(value);
                ReportPropertyChanging("numberHitsForFalsePositiveCurrent");
                _numberHitsForFalsePositiveCurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberHitsForFalsePositiveCurrent");
                OnnumberHitsForFalsePositiveCurrentChanged();
            }
        }
        private global::System.String _numberHitsForFalsePositiveCurrent;
        partial void OnnumberHitsForFalsePositiveCurrentChanging(global::System.String value);
        partial void OnnumberHitsForFalsePositiveCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberMisses24Hour
        {
            get
            {
                return _numberMisses24Hour;
            }
            set
            {
                OnnumberMisses24HourChanging(value);
                ReportPropertyChanging("numberMisses24Hour");
                _numberMisses24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberMisses24Hour");
                OnnumberMisses24HourChanged();
            }
        }
        private global::System.String _numberMisses24Hour;
        partial void OnnumberMisses24HourChanging(global::System.String value);
        partial void OnnumberMisses24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberMissesCurrent
        {
            get
            {
                return _numberMissesCurrent;
            }
            set
            {
                OnnumberMissesCurrentChanging(value);
                ReportPropertyChanging("numberMissesCurrent");
                _numberMissesCurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberMissesCurrent");
                OnnumberMissesCurrentChanged();
            }
        }
        private global::System.String _numberMissesCurrent;
        partial void OnnumberMissesCurrentChanging(global::System.String value);
        partial void OnnumberMissesCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOFCOMAbandons24Hour
        {
            get
            {
                return _numberOFCOMAbandons24Hour;
            }
            set
            {
                OnnumberOFCOMAbandons24HourChanging(value);
                ReportPropertyChanging("numberOFCOMAbandons24Hour");
                _numberOFCOMAbandons24Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOFCOMAbandons24Hour");
                OnnumberOFCOMAbandons24HourChanged();
            }
        }
        private global::System.String _numberOFCOMAbandons24Hour;
        partial void OnnumberOFCOMAbandons24HourChanging(global::System.String value);
        partial void OnnumberOFCOMAbandons24HourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOFCOMAbandonsCurrent
        {
            get
            {
                return _numberOFCOMAbandonsCurrent;
            }
            set
            {
                OnnumberOFCOMAbandonsCurrentChanging(value);
                ReportPropertyChanging("numberOFCOMAbandonsCurrent");
                _numberOFCOMAbandonsCurrent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOFCOMAbandonsCurrent");
                OnnumberOFCOMAbandonsCurrentChanged();
            }
        }
        private global::System.String _numberOFCOMAbandonsCurrent;
        partial void OnnumberOFCOMAbandonsCurrentChanging(global::System.String value);
        partial void OnnumberOFCOMAbandonsCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfRecoveries
        {
            get
            {
                return _numberOfRecoveries;
            }
            set
            {
                OnnumberOfRecoveriesChanging(value);
                ReportPropertyChanging("numberOfRecoveries");
                _numberOfRecoveries = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfRecoveries");
                OnnumberOfRecoveriesChanged();
            }
        }
        private global::System.String _numberOfRecoveries;
        partial void OnnumberOfRecoveriesChanging(global::System.String value);
        partial void OnnumberOfRecoveriesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfSales
        {
            get
            {
                return _numberOfSales;
            }
            set
            {
                OnnumberOfSalesChanging(value);
                ReportPropertyChanging("numberOfSales");
                _numberOfSales = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfSales");
                OnnumberOfSalesChanged();
            }
        }
        private global::System.String _numberOfSales;
        partial void OnnumberOfSalesChanging(global::System.String value);
        partial void OnnumberOfSalesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String peakHourCallRate
        {
            get
            {
                return _peakHourCallRate;
            }
            set
            {
                OnpeakHourCallRateChanging(value);
                ReportPropertyChanging("peakHourCallRate");
                _peakHourCallRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("peakHourCallRate");
                OnpeakHourCallRateChanged();
            }
        }
        private global::System.String _peakHourCallRate;
        partial void OnpeakHourCallRateChanging(global::System.String value);
        partial void OnpeakHourCallRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playMessage
        {
            get
            {
                return _playMessage;
            }
            set
            {
                OnplayMessageChanging(value);
                ReportPropertyChanging("playMessage");
                _playMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playMessage");
                OnplayMessageChanged();
            }
        }
        private global::System.String _playMessage;
        partial void OnplayMessageChanging(global::System.String value);
        partial void OnplayMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playMessageFailure
        {
            get
            {
                return _playMessageFailure;
            }
            set
            {
                OnplayMessageFailureChanging(value);
                ReportPropertyChanging("playMessageFailure");
                _playMessageFailure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playMessageFailure");
                OnplayMessageFailureChanged();
            }
        }
        private global::System.String _playMessageFailure;
        partial void OnplayMessageFailureChanging(global::System.String value);
        partial void OnplayMessageFailureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playMessageTimeSuccess
        {
            get
            {
                return _playMessageTimeSuccess;
            }
            set
            {
                OnplayMessageTimeSuccessChanging(value);
                ReportPropertyChanging("playMessageTimeSuccess");
                _playMessageTimeSuccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playMessageTimeSuccess");
                OnplayMessageTimeSuccessChanged();
            }
        }
        private global::System.String _playMessageTimeSuccess;
        partial void OnplayMessageTimeSuccessChanging(global::System.String value);
        partial void OnplayMessageTimeSuccessChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playMessageTimeViolation
        {
            get
            {
                return _playMessageTimeViolation;
            }
            set
            {
                OnplayMessageTimeViolationChanging(value);
                ReportPropertyChanging("playMessageTimeViolation");
                _playMessageTimeViolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playMessageTimeViolation");
                OnplayMessageTimeViolationChanged();
            }
        }
        private global::System.String _playMessageTimeViolation;
        partial void OnplayMessageTimeViolationChanging(global::System.String value);
        partial void OnplayMessageTimeViolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String playScript
        {
            get
            {
                return _playScript;
            }
            set
            {
                OnplayScriptChanging(value);
                ReportPropertyChanging("playScript");
                _playScript = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("playScript");
                OnplayScriptChanged();
            }
        }
        private global::System.String _playScript;
        partial void OnplayScriptChanging(global::System.String value);
        partial void OnplayScriptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recoveryTimeBegin
        {
            get
            {
                return _recoveryTimeBegin;
            }
            set
            {
                OnrecoveryTimeBeginChanging(value);
                ReportPropertyChanging("recoveryTimeBegin");
                _recoveryTimeBegin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recoveryTimeBegin");
                OnrecoveryTimeBeginChanged();
            }
        }
        private global::System.String _recoveryTimeBegin;
        partial void OnrecoveryTimeBeginChanging(global::System.String value);
        partial void OnrecoveryTimeBeginChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recoveryTimeEnd
        {
            get
            {
                return _recoveryTimeEnd;
            }
            set
            {
                OnrecoveryTimeEndChanging(value);
                ReportPropertyChanging("recoveryTimeEnd");
                _recoveryTimeEnd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recoveryTimeEnd");
                OnrecoveryTimeEndChanged();
            }
        }
        private global::System.String _recoveryTimeEnd;
        partial void OnrecoveryTimeEndChanging(global::System.String value);
        partial void OnrecoveryTimeEndChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ringNoAnswerViolation
        {
            get
            {
                return _ringNoAnswerViolation;
            }
            set
            {
                OnringNoAnswerViolationChanging(value);
                ReportPropertyChanging("ringNoAnswerViolation");
                _ringNoAnswerViolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ringNoAnswerViolation");
                OnringNoAnswerViolationChanged();
            }
        }
        private global::System.String _ringNoAnswerViolation;
        partial void OnringNoAnswerViolationChanging(global::System.String value);
        partial void OnringNoAnswerViolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String scheduledCallbacks
        {
            get
            {
                return _scheduledCallbacks;
            }
            set
            {
                OnscheduledCallbacksChanging(value);
                ReportPropertyChanging("scheduledCallbacks");
                _scheduledCallbacks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("scheduledCallbacks");
                OnscheduledCallbacksChanged();
            }
        }
        private global::System.String _scheduledCallbacks;
        partial void OnscheduledCallbacksChanging(global::System.String value);
        partial void OnscheduledCallbacksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sendDigits
        {
            get
            {
                return _sendDigits;
            }
            set
            {
                OnsendDigitsChanging(value);
                ReportPropertyChanging("sendDigits");
                _sendDigits = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sendDigits");
                OnsendDigitsChanged();
            }
        }
        private global::System.String _sendDigits;
        partial void OnsendDigitsChanging(global::System.String value);
        partial void OnsendDigitsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sendFax
        {
            get
            {
                return _sendFax;
            }
            set
            {
                OnsendFaxChanging(value);
                ReportPropertyChanging("sendFax");
                _sendFax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sendFax");
                OnsendFaxChanged();
            }
        }
        private global::System.String _sendFax;
        partial void OnsendFaxChanging(global::System.String value);
        partial void OnsendFaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneIdentifier
        {
            get
            {
                return _timezoneIdentifier;
            }
            set
            {
                OntimezoneIdentifierChanging(value);
                ReportPropertyChanging("timezoneIdentifier");
                _timezoneIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneIdentifier");
                OntimezoneIdentifierChanged();
            }
        }
        private global::System.String _timezoneIdentifier;
        partial void OntimezoneIdentifierChanging(global::System.String value);
        partial void OntimezoneIdentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferTimeSuccess
        {
            get
            {
                return _transferTimeSuccess;
            }
            set
            {
                OntransferTimeSuccessChanging(value);
                ReportPropertyChanging("transferTimeSuccess");
                _transferTimeSuccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferTimeSuccess");
                OntransferTimeSuccessChanged();
            }
        }
        private global::System.String _transferTimeSuccess;
        partial void OntransferTimeSuccessChanging(global::System.String value);
        partial void OntransferTimeSuccessChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferTimeViolation
        {
            get
            {
                return _transferTimeViolation;
            }
            set
            {
                OntransferTimeViolationChanging(value);
                ReportPropertyChanging("transferTimeViolation");
                _transferTimeViolation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferTimeViolation");
                OntransferTimeViolationChanged();
            }
        }
        private global::System.String _transferTimeViolation;
        partial void OntransferTimeViolationChanging(global::System.String value);
        partial void OntransferTimeViolationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferCoConnectAverage
        {
            get
            {
                return _transferCoConnectAverage;
            }
            set
            {
                OntransferCoConnectAverageChanging(value);
                ReportPropertyChanging("transferCoConnectAverage");
                _transferCoConnectAverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferCoConnectAverage");
                OntransferCoConnectAverageChanged();
            }
        }
        private global::System.String _transferCoConnectAverage;
        partial void OntransferCoConnectAverageChanging(global::System.String value);
        partial void OntransferCoConnectAverageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferToConnectHigh
        {
            get
            {
                return _transferToConnectHigh;
            }
            set
            {
                OntransferToConnectHighChanging(value);
                ReportPropertyChanging("transferToConnectHigh");
                _transferToConnectHigh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferToConnectHigh");
                OntransferToConnectHighChanged();
            }
        }
        private global::System.String _transferToConnectHigh;
        partial void OntransferToConnectHighChanging(global::System.String value);
        partial void OntransferToConnectHighChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferToConnectLow
        {
            get
            {
                return _transferToConnectLow;
            }
            set
            {
                OntransferToConnectLowChanging(value);
                ReportPropertyChanging("transferToConnectLow");
                _transferToConnectLow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferToConnectLow");
                OntransferToConnectLowChanged();
            }
        }
        private global::System.String _transferToConnectLow;
        partial void OntransferToConnectLowChanging(global::System.String value);
        partial void OntransferToConnectLowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStartTime
        {
            get
            {
                return _utcStartTime;
            }
            set
            {
                OnutcStartTimeChanging(value);
                ReportPropertyChanging("utcStartTime");
                _utcStartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStartTime");
                OnutcStartTimeChanged();
            }
        }
        private global::System.String _utcStartTime;
        partial void OnutcStartTimeChanging(global::System.String value);
        partial void OnutcStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStopTime
        {
            get
            {
                return _utcStopTime;
            }
            set
            {
                OnutcStopTimeChanging(value);
                ReportPropertyChanging("utcStopTime");
                _utcStopTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStopTime");
                OnutcStopTimeChanged();
            }
        }
        private global::System.String _utcStopTime;
        partial void OnutcStopTimeChanging(global::System.String value);
        partial void OnutcStopTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String getAodData
        {
            get
            {
                return _getAodData;
            }
            set
            {
                OngetAodDataChanging(value);
                ReportPropertyChanging("getAodData");
                _getAodData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("getAodData");
                OngetAodDataChanged();
            }
        }
        private global::System.String _getAodData;
        partial void OngetAodDataChanging(global::System.String value);
        partial void OngetAodDataChanged();

        #endregion

    
    }

    #endregion

    
}
