//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities_resourcegroup : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities_resourcegroup”部分中的连接字符串初始化新 testEntities_resourcegroup 对象。
        /// </summary>
        public testEntities_resourcegroup() : base("name=testEntities_resourcegroup", "testEntities_resourcegroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_resourcegroup 对象。
        /// </summary>
        public testEntities_resourcegroup(string connectionString) : base(connectionString, "testEntities_resourcegroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_resourcegroup 对象。
        /// </summary>
        public testEntities_resourcegroup(EntityConnection connection) : base(connection, "testEntities_resourcegroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_rgstats2> crm_aspect_monitor_rgstats2
        {
            get
            {
                if ((_crm_aspect_monitor_rgstats2 == null))
                {
                    _crm_aspect_monitor_rgstats2 = base.CreateObjectSet<crm_aspect_monitor_rgstats2>("crm_aspect_monitor_rgstats2");
                }
                return _crm_aspect_monitor_rgstats2;
            }
        }
        private ObjectSet<crm_aspect_monitor_rgstats2> _crm_aspect_monitor_rgstats2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_rgstats2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_rgstats2(crm_aspect_monitor_rgstats2 crm_aspect_monitor_rgstats2)
        {
            base.AddObject("crm_aspect_monitor_rgstats2", crm_aspect_monitor_rgstats2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel5", Name="crm_aspect_monitor_rgstats2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_rgstats2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_rgstats2 对象。
        /// </summary>
        /// <param name="resourceGroupId">resourceGroupId 属性的初始值。</param>
        public static crm_aspect_monitor_rgstats2 Createcrm_aspect_monitor_rgstats2(global::System.String resourceGroupId)
        {
            crm_aspect_monitor_rgstats2 crm_aspect_monitor_rgstats2 = new crm_aspect_monitor_rgstats2();
            crm_aspect_monitor_rgstats2.resourceGroupId = resourceGroupId;
            return crm_aspect_monitor_rgstats2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private global::System.String _createtime;
        partial void OncreatetimeChanging(global::System.String value);
        partial void OncreatetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String allChannelsBusy
        {
            get
            {
                return _allChannelsBusy;
            }
            set
            {
                OnallChannelsBusyChanging(value);
                ReportPropertyChanging("allChannelsBusy");
                _allChannelsBusy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("allChannelsBusy");
                OnallChannelsBusyChanged();
            }
        }
        private global::System.String _allChannelsBusy;
        partial void OnallChannelsBusyChanging(global::System.String value);
        partial void OnallChannelsBusyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numBusyChannels
        {
            get
            {
                return _numBusyChannels;
            }
            set
            {
                OnnumBusyChannelsChanging(value);
                ReportPropertyChanging("numBusyChannels");
                _numBusyChannels = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numBusyChannels");
                OnnumBusyChannelsChanged();
            }
        }
        private global::System.String _numBusyChannels;
        partial void OnnumBusyChannelsChanging(global::System.String value);
        partial void OnnumBusyChannelsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numIdleChannels
        {
            get
            {
                return _numIdleChannels;
            }
            set
            {
                OnnumIdleChannelsChanging(value);
                ReportPropertyChanging("numIdleChannels");
                _numIdleChannels = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numIdleChannels");
                OnnumIdleChannelsChanged();
            }
        }
        private global::System.String _numIdleChannels;
        partial void OnnumIdleChannelsChanging(global::System.String value);
        partial void OnnumIdleChannelsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String percentOfBusyState
        {
            get
            {
                return _percentOfBusyState;
            }
            set
            {
                OnpercentOfBusyStateChanging(value);
                ReportPropertyChanging("percentOfBusyState");
                _percentOfBusyState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("percentOfBusyState");
                OnpercentOfBusyStateChanged();
            }
        }
        private global::System.String _percentOfBusyState;
        partial void OnpercentOfBusyStateChanging(global::System.String value);
        partial void OnpercentOfBusyStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String percentOfIdleState
        {
            get
            {
                return _percentOfIdleState;
            }
            set
            {
                OnpercentOfIdleStateChanging(value);
                ReportPropertyChanging("percentOfIdleState");
                _percentOfIdleState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("percentOfIdleState");
                OnpercentOfIdleStateChanged();
            }
        }
        private global::System.String _percentOfIdleState;
        partial void OnpercentOfIdleStateChanging(global::System.String value);
        partial void OnpercentOfIdleStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String resourceGroupId
        {
            get
            {
                return _resourceGroupId;
            }
            set
            {
                if (_resourceGroupId != value)
                {
                    OnresourceGroupIdChanging(value);
                    ReportPropertyChanging("resourceGroupId");
                    _resourceGroupId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("resourceGroupId");
                    OnresourceGroupIdChanged();
                }
            }
        }
        private global::System.String _resourceGroupId;
        partial void OnresourceGroupIdChanging(global::System.String value);
        partial void OnresourceGroupIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resourceGroup
        {
            get
            {
                return _resourceGroup;
            }
            set
            {
                OnresourceGroupChanging(value);
                ReportPropertyChanging("resourceGroup");
                _resourceGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resourceGroup");
                OnresourceGroupChanged();
            }
        }
        private global::System.String _resourceGroup;
        partial void OnresourceGroupChanging(global::System.String value);
        partial void OnresourceGroupChanged();

        #endregion

    
    }

    #endregion

    
}
