//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities_table : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities_table”部分中的连接字符串初始化新 testEntities_table 对象。
        /// </summary>
        public testEntities_table() : base("name=testEntities_table", "testEntities_table")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_table 对象。
        /// </summary>
        public testEntities_table(string connectionString) : base(connectionString, "testEntities_table")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_table 对象。
        /// </summary>
        public testEntities_table(EntityConnection connection) : base(connection, "testEntities_table")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_table2> crm_aspect_monitor_table2
        {
            get
            {
                if ((_crm_aspect_monitor_table2 == null))
                {
                    _crm_aspect_monitor_table2 = base.CreateObjectSet<crm_aspect_monitor_table2>("crm_aspect_monitor_table2");
                }
                return _crm_aspect_monitor_table2;
            }
        }
        private ObjectSet<crm_aspect_monitor_table2> _crm_aspect_monitor_table2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_table2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_table2(crm_aspect_monitor_table2 crm_aspect_monitor_table2)
        {
            base.AddObject("crm_aspect_monitor_table2", crm_aspect_monitor_table2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel4", Name="crm_aspect_monitor_table2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_table2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_table2 对象。
        /// </summary>
        /// <param name="tableId">tableId 属性的初始值。</param>
        public static crm_aspect_monitor_table2 Createcrm_aspect_monitor_table2(global::System.String tableId)
        {
            crm_aspect_monitor_table2 crm_aspect_monitor_table2 = new crm_aspect_monitor_table2();
            crm_aspect_monitor_table2.tableId = tableId;
            return crm_aspect_monitor_table2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tableId
        {
            get
            {
                return _tableId;
            }
            set
            {
                if (_tableId != value)
                {
                    OntableIdChanging(value);
                    ReportPropertyChanging("tableId");
                    _tableId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("tableId");
                    OntableIdChanged();
                }
            }
        }
        private global::System.String _tableId;
        partial void OntableIdChanging(global::System.String value);
        partial void OntableIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String filter
        {
            get
            {
                return _filter;
            }
            set
            {
                OnfilterChanging(value);
                ReportPropertyChanging("filter");
                _filter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("filter");
                OnfilterChanged();
            }
        }
        private global::System.String _filter;
        partial void OnfilterChanging(global::System.String value);
        partial void OnfilterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service
        {
            get
            {
                return _service;
            }
            set
            {
                OnserviceChanging(value);
                ReportPropertyChanging("service");
                _service = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service");
                OnserviceChanged();
            }
        }
        private global::System.String _service;
        partial void OnserviceChanging(global::System.String value);
        partial void OnserviceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String application
        {
            get
            {
                return _application;
            }
            set
            {
                OnapplicationChanging(value);
                ReportPropertyChanging("application");
                _application = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("application");
                OnapplicationChanged();
            }
        }
        private global::System.String _application;
        partial void OnapplicationChanging(global::System.String value);
        partial void OnapplicationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.String _applicationId;
        partial void OnapplicationIdChanging(global::System.String value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceId
        {
            get
            {
                return _serviceId;
            }
            set
            {
                OnserviceIdChanging(value);
                ReportPropertyChanging("serviceId");
                _serviceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceId");
                OnserviceIdChanged();
            }
        }
        private global::System.String _serviceId;
        partial void OnserviceIdChanging(global::System.String value);
        partial void OnserviceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceType
        {
            get
            {
                return _serviceType;
            }
            set
            {
                OnserviceTypeChanging(value);
                ReportPropertyChanging("serviceType");
                _serviceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceType");
                OnserviceTypeChanged();
            }
        }
        private global::System.String _serviceType;
        partial void OnserviceTypeChanging(global::System.String value);
        partial void OnserviceTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceTypeId
        {
            get
            {
                return _serviceTypeId;
            }
            set
            {
                OnserviceTypeIdChanging(value);
                ReportPropertyChanging("serviceTypeId");
                _serviceTypeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceTypeId");
                OnserviceTypeIdChanged();
            }
        }
        private global::System.String _serviceTypeId;
        partial void OnserviceTypeIdChanging(global::System.String value);
        partial void OnserviceTypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String startTimeMilitary
        {
            get
            {
                return _startTimeMilitary;
            }
            set
            {
                OnstartTimeMilitaryChanging(value);
                ReportPropertyChanging("startTimeMilitary");
                _startTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("startTimeMilitary");
                OnstartTimeMilitaryChanged();
            }
        }
        private global::System.String _startTimeMilitary;
        partial void OnstartTimeMilitaryChanging(global::System.String value);
        partial void OnstartTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.String _statusId;
        partial void OnstatusIdChanging(global::System.String value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String scheduledCallbacks
        {
            get
            {
                return _scheduledCallbacks;
            }
            set
            {
                OnscheduledCallbacksChanging(value);
                ReportPropertyChanging("scheduledCallbacks");
                _scheduledCallbacks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("scheduledCallbacks");
                OnscheduledCallbacksChanged();
            }
        }
        private global::System.String _scheduledCallbacks;
        partial void OnscheduledCallbacksChanging(global::System.String value);
        partial void OnscheduledCallbacksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String abandoned
        {
            get
            {
                return _abandoned;
            }
            set
            {
                OnabandonedChanging(value);
                ReportPropertyChanging("abandoned");
                _abandoned = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abandoned");
                OnabandonedChanged();
            }
        }
        private global::System.String _abandoned;
        partial void OnabandonedChanging(global::System.String value);
        partial void OnabandonedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String badPhoneNumberCount
        {
            get
            {
                return _badPhoneNumberCount;
            }
            set
            {
                OnbadPhoneNumberCountChanging(value);
                ReportPropertyChanging("badPhoneNumberCount");
                _badPhoneNumberCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("badPhoneNumberCount");
                OnbadPhoneNumberCountChanged();
            }
        }
        private global::System.String _badPhoneNumberCount;
        partial void OnbadPhoneNumberCountChanging(global::System.String value);
        partial void OnbadPhoneNumberCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dialed
        {
            get
            {
                return _dialed;
            }
            set
            {
                OndialedChanging(value);
                ReportPropertyChanging("dialed");
                _dialed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dialed");
                OndialedChanged();
            }
        }
        private global::System.String _dialed;
        partial void OndialedChanging(global::System.String value);
        partial void OndialedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endTimeMilitary
        {
            get
            {
                return _endTimeMilitary;
            }
            set
            {
                OnendTimeMilitaryChanging(value);
                ReportPropertyChanging("endTimeMilitary");
                _endTimeMilitary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endTimeMilitary");
                OnendTimeMilitaryChanged();
            }
        }
        private global::System.String _endTimeMilitary;
        partial void OnendTimeMilitaryChanging(global::System.String value);
        partial void OnendTimeMilitaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String excludedCount
        {
            get
            {
                return _excludedCount;
            }
            set
            {
                OnexcludedCountChanging(value);
                ReportPropertyChanging("excludedCount");
                _excludedCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("excludedCount");
                OnexcludedCountChanged();
            }
        }
        private global::System.String _excludedCount;
        partial void OnexcludedCountChanging(global::System.String value);
        partial void OnexcludedCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String filterId
        {
            get
            {
                return _filterId;
            }
            set
            {
                OnfilterIdChanging(value);
                ReportPropertyChanging("filterId");
                _filterId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("filterId");
                OnfilterIdChanged();
            }
        }
        private global::System.String _filterId;
        partial void OnfilterIdChanging(global::System.String value);
        partial void OnfilterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String inProgress
        {
            get
            {
                return _inProgress;
            }
            set
            {
                OninProgressChanging(value);
                ReportPropertyChanging("inProgress");
                _inProgress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("inProgress");
                OninProgressChanged();
            }
        }
        private global::System.String _inProgress;
        partial void OninProgressChanging(global::System.String value);
        partial void OninProgressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String leftToBeDialed
        {
            get
            {
                return _leftToBeDialed;
            }
            set
            {
                OnleftToBeDialedChanging(value);
                ReportPropertyChanging("leftToBeDialed");
                _leftToBeDialed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("leftToBeDialed");
                OnleftToBeDialedChanged();
            }
        }
        private global::System.String _leftToBeDialed;
        partial void OnleftToBeDialedChanging(global::System.String value);
        partial void OnleftToBeDialedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recordsProcessed
        {
            get
            {
                return _recordsProcessed;
            }
            set
            {
                OnrecordsProcessedChanging(value);
                ReportPropertyChanging("recordsProcessed");
                _recordsProcessed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recordsProcessed");
                OnrecordsProcessedChanged();
            }
        }
        private global::System.String _recordsProcessed;
        partial void OnrecordsProcessedChanging(global::System.String value);
        partial void OnrecordsProcessedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rgBusyQueueCount
        {
            get
            {
                return _rgBusyQueueCount;
            }
            set
            {
                OnrgBusyQueueCountChanging(value);
                ReportPropertyChanging("rgBusyQueueCount");
                _rgBusyQueueCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rgBusyQueueCount");
                OnrgBusyQueueCountChanged();
            }
        }
        private global::System.String _rgBusyQueueCount;
        partial void OnrgBusyQueueCountChanging(global::System.String value);
        partial void OnrgBusyQueueCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String selected
        {
            get
            {
                return _selected;
            }
            set
            {
                OnselectedChanging(value);
                ReportPropertyChanging("selected");
                _selected = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("selected");
                OnselectedChanged();
            }
        }
        private global::System.String _selected;
        partial void OnselectedChanging(global::System.String value);
        partial void OnselectedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serviceTableId
        {
            get
            {
                return _serviceTableId;
            }
            set
            {
                OnserviceTableIdChanging(value);
                ReportPropertyChanging("serviceTableId");
                _serviceTableId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serviceTableId");
                OnserviceTableIdChanged();
            }
        }
        private global::System.String _serviceTableId;
        partial void OnserviceTableIdChanging(global::System.String value);
        partial void OnserviceTableIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tableName
        {
            get
            {
                return _tableName;
            }
            set
            {
                OntableNameChanging(value);
                ReportPropertyChanging("tableName");
                _tableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tableName");
                OntableNameChanged();
            }
        }
        private global::System.String _tableName;
        partial void OntableNameChanging(global::System.String value);
        partial void OntableNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneFailureCount
        {
            get
            {
                return _timezoneFailureCount;
            }
            set
            {
                OntimezoneFailureCountChanging(value);
                ReportPropertyChanging("timezoneFailureCount");
                _timezoneFailureCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneFailureCount");
                OntimezoneFailureCountChanged();
            }
        }
        private global::System.String _timezoneFailureCount;
        partial void OntimezoneFailureCountChanging(global::System.String value);
        partial void OntimezoneFailureCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String touchedcount
        {
            get
            {
                return _touchedcount;
            }
            set
            {
                OntouchedcountChanging(value);
                ReportPropertyChanging("touchedcount");
                _touchedcount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("touchedcount");
                OntouchedcountChanged();
            }
        }
        private global::System.String _touchedcount;
        partial void OntouchedcountChanging(global::System.String value);
        partial void OntouchedcountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezoneIdentifier
        {
            get
            {
                return _timezoneIdentifier;
            }
            set
            {
                OntimezoneIdentifierChanging(value);
                ReportPropertyChanging("timezoneIdentifier");
                _timezoneIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezoneIdentifier");
                OntimezoneIdentifierChanged();
            }
        }
        private global::System.String _timezoneIdentifier;
        partial void OntimezoneIdentifierChanging(global::System.String value);
        partial void OntimezoneIdentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStartTime
        {
            get
            {
                return _utcStartTime;
            }
            set
            {
                OnutcStartTimeChanging(value);
                ReportPropertyChanging("utcStartTime");
                _utcStartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStartTime");
                OnutcStartTimeChanged();
            }
        }
        private global::System.String _utcStartTime;
        partial void OnutcStartTimeChanging(global::System.String value);
        partial void OnutcStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utcStopTime
        {
            get
            {
                return _utcStopTime;
            }
            set
            {
                OnutcStopTimeChanging(value);
                ReportPropertyChanging("utcStopTime");
                _utcStopTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("utcStopTime");
                OnutcStopTimeChanged();
            }
        }
        private global::System.String _utcStopTime;
        partial void OnutcStopTimeChanging(global::System.String value);
        partial void OnutcStopTimeChanged();

        #endregion

    
    }

    #endregion

    
}
