//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OSMSClient
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class testEntities_wrokgroup : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“testEntities_wrokgroup”部分中的连接字符串初始化新 testEntities_wrokgroup 对象。
        /// </summary>
        public testEntities_wrokgroup() : base("name=testEntities_wrokgroup", "testEntities_wrokgroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_wrokgroup 对象。
        /// </summary>
        public testEntities_wrokgroup(string connectionString) : base(connectionString, "testEntities_wrokgroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 testEntities_wrokgroup 对象。
        /// </summary>
        public testEntities_wrokgroup(EntityConnection connection) : base(connection, "testEntities_wrokgroup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<crm_aspect_monitor_workgroup2> crm_aspect_monitor_workgroup2
        {
            get
            {
                if ((_crm_aspect_monitor_workgroup2 == null))
                {
                    _crm_aspect_monitor_workgroup2 = base.CreateObjectSet<crm_aspect_monitor_workgroup2>("crm_aspect_monitor_workgroup2");
                }
                return _crm_aspect_monitor_workgroup2;
            }
        }
        private ObjectSet<crm_aspect_monitor_workgroup2> _crm_aspect_monitor_workgroup2;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 crm_aspect_monitor_workgroup2 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocrm_aspect_monitor_workgroup2(crm_aspect_monitor_workgroup2 crm_aspect_monitor_workgroup2)
        {
            base.AddObject("crm_aspect_monitor_workgroup2", crm_aspect_monitor_workgroup2);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel3", Name="crm_aspect_monitor_workgroup2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class crm_aspect_monitor_workgroup2 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 crm_aspect_monitor_workgroup2 对象。
        /// </summary>
        /// <param name="workgroupId">workgroupId 属性的初始值。</param>
        public static crm_aspect_monitor_workgroup2 Createcrm_aspect_monitor_workgroup2(global::System.String workgroupId)
        {
            crm_aspect_monitor_workgroup2 crm_aspect_monitor_workgroup2 = new crm_aspect_monitor_workgroup2();
            crm_aspect_monitor_workgroup2.workgroupId = workgroupId;
            return crm_aspect_monitor_workgroup2;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String workgroupId
        {
            get
            {
                return _workgroupId;
            }
            set
            {
                if (_workgroupId != value)
                {
                    OnworkgroupIdChanging(value);
                    ReportPropertyChanging("workgroupId");
                    _workgroupId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("workgroupId");
                    OnworkgroupIdChanged();
                }
            }
        }
        private global::System.String _workgroupId;
        partial void OnworkgroupIdChanging(global::System.String value);
        partial void OnworkgroupIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptSeconds
        {
            get
            {
                return _acceptSeconds;
            }
            set
            {
                OnacceptSecondsChanging(value);
                ReportPropertyChanging("acceptSeconds");
                _acceptSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptSeconds");
                OnacceptSecondsChanged();
            }
        }
        private global::System.String _acceptSeconds;
        partial void OnacceptSecondsChanging(global::System.String value);
        partial void OnacceptSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acdCalls
        {
            get
            {
                return _acdCalls;
            }
            set
            {
                OnacdCallsChanging(value);
                ReportPropertyChanging("acdCalls");
                _acdCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acdCalls");
                OnacdCallsChanged();
            }
        }
        private global::System.String _acdCalls;
        partial void OnacdCallsChanging(global::System.String value);
        partial void OnacdCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String activeSeconds
        {
            get
            {
                return _activeSeconds;
            }
            set
            {
                OnactiveSecondsChanging(value);
                ReportPropertyChanging("activeSeconds");
                _activeSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("activeSeconds");
                OnactiveSecondsChanged();
            }
        }
        private global::System.String _activeSeconds;
        partial void OnactiveSecondsChanging(global::System.String value);
        partial void OnactiveSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agdCalls
        {
            get
            {
                return _agdCalls;
            }
            set
            {
                OnagdCallsChanging(value);
                ReportPropertyChanging("agdCalls");
                _agdCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agdCalls");
                OnagdCallsChanged();
            }
        }
        private global::System.String _agdCalls;
        partial void OnagdCallsChanging(global::System.String value);
        partial void OnagdCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aodCalls
        {
            get
            {
                return _aodCalls;
            }
            set
            {
                OnaodCallsChanging(value);
                ReportPropertyChanging("aodCalls");
                _aodCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aodCalls");
                OnaodCallsChanged();
            }
        }
        private global::System.String _aodCalls;
        partial void OnaodCallsChanging(global::System.String value);
        partial void OnaodCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String chatCalls
        {
            get
            {
                return _chatCalls;
            }
            set
            {
                OnchatCallsChanging(value);
                ReportPropertyChanging("chatCalls");
                _chatCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("chatCalls");
                OnchatCallsChanged();
            }
        }
        private global::System.String _chatCalls;
        partial void OnchatCallsChanging(global::System.String value);
        partial void OnchatCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String conferenceCalls
        {
            get
            {
                return _conferenceCalls;
            }
            set
            {
                OnconferenceCallsChanging(value);
                ReportPropertyChanging("conferenceCalls");
                _conferenceCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("conferenceCalls");
                OnconferenceCallsChanged();
            }
        }
        private global::System.String _conferenceCalls;
        partial void OnconferenceCallsChanging(global::System.String value);
        partial void OnconferenceCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String connectSeconds
        {
            get
            {
                return _connectSeconds;
            }
            set
            {
                OnconnectSecondsChanging(value);
                ReportPropertyChanging("connectSeconds");
                _connectSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("connectSeconds");
                OnconnectSecondsChanged();
            }
        }
        private global::System.String _connectSeconds;
        partial void OnconnectSecondsChanging(global::System.String value);
        partial void OnconnectSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String consultationCalls
        {
            get
            {
                return _consultationCalls;
            }
            set
            {
                OnconsultationCallsChanging(value);
                ReportPropertyChanging("consultationCalls");
                _consultationCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("consultationCalls");
                OnconsultationCallsChanged();
            }
        }
        private global::System.String _consultationCalls;
        partial void OnconsultationCallsChanging(global::System.String value);
        partial void OnconsultationCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ctiCalls
        {
            get
            {
                return _ctiCalls;
            }
            set
            {
                OnctiCallsChanging(value);
                ReportPropertyChanging("ctiCalls");
                _ctiCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ctiCalls");
                OnctiCallsChanged();
            }
        }
        private global::System.String _ctiCalls;
        partial void OnctiCallsChanging(global::System.String value);
        partial void OnctiCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String didCalls
        {
            get
            {
                return _didCalls;
            }
            set
            {
                OndidCallsChanging(value);
                ReportPropertyChanging("didCalls");
                _didCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("didCalls");
                OndidCallsChanged();
            }
        }
        private global::System.String _didCalls;
        partial void OndidCallsChanging(global::System.String value);
        partial void OndidCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailCalls
        {
            get
            {
                return _emailCalls;
            }
            set
            {
                OnemailCallsChanging(value);
                ReportPropertyChanging("emailCalls");
                _emailCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailCalls");
                OnemailCallsChanged();
            }
        }
        private global::System.String _emailCalls;
        partial void OnemailCallsChanging(global::System.String value);
        partial void OnemailCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String heldCalls
        {
            get
            {
                return _heldCalls;
            }
            set
            {
                OnheldCallsChanging(value);
                ReportPropertyChanging("heldCalls");
                _heldCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("heldCalls");
                OnheldCallsChanged();
            }
        }
        private global::System.String _heldCalls;
        partial void OnheldCallsChanging(global::System.String value);
        partial void OnheldCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String heldCeconds
        {
            get
            {
                return _heldCeconds;
            }
            set
            {
                OnheldCecondsChanging(value);
                ReportPropertyChanging("heldCeconds");
                _heldCeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("heldCeconds");
                OnheldCecondsChanged();
            }
        }
        private global::System.String _heldCeconds;
        partial void OnheldCecondsChanging(global::System.String value);
        partial void OnheldCecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idleCeconds
        {
            get
            {
                return _idleCeconds;
            }
            set
            {
                OnidleCecondsChanging(value);
                ReportPropertyChanging("idleCeconds");
                _idleCeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idleCeconds");
                OnidleCecondsChanged();
            }
        }
        private global::System.String _idleCeconds;
        partial void OnidleCecondsChanging(global::System.String value);
        partial void OnidleCecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imCalls
        {
            get
            {
                return _imCalls;
            }
            set
            {
                OnimCallsChanging(value);
                ReportPropertyChanging("imCalls");
                _imCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imCalls");
                OnimCallsChanged();
            }
        }
        private global::System.String _imCalls;
        partial void OnimCallsChanging(global::System.String value);
        partial void OnimCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String internalCalls
        {
            get
            {
                return _internalCalls;
            }
            set
            {
                OninternalCallsChanging(value);
                ReportPropertyChanging("internalCalls");
                _internalCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("internalCalls");
                OninternalCallsChanged();
            }
        }
        private global::System.String _internalCalls;
        partial void OninternalCallsChanging(global::System.String value);
        partial void OninternalCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String internalSeconds
        {
            get
            {
                return _internalSeconds;
            }
            set
            {
                OninternalSecondsChanging(value);
                ReportPropertyChanging("internalSeconds");
                _internalSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("internalSeconds");
                OninternalSecondsChanged();
            }
        }
        private global::System.String _internalSeconds;
        partial void OninternalSecondsChanging(global::System.String value);
        partial void OninternalSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loggedinSeconds
        {
            get
            {
                return _loggedinSeconds;
            }
            set
            {
                OnloggedinSecondsChanging(value);
                ReportPropertyChanging("loggedinSeconds");
                _loggedinSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loggedinSeconds");
                OnloggedinSecondsChanged();
            }
        }
        private global::System.String _loggedinSeconds;
        partial void OnloggedinSecondsChanging(global::System.String value);
        partial void OnloggedinSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manualCalls
        {
            get
            {
                return _manualCalls;
            }
            set
            {
                OnmanualCallsChanging(value);
                ReportPropertyChanging("manualCalls");
                _manualCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manualCalls");
                OnmanualCallsChanged();
            }
        }
        private global::System.String _manualCalls;
        partial void OnmanualCallsChanging(global::System.String value);
        partial void OnmanualCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manualSeconds
        {
            get
            {
                return _manualSeconds;
            }
            set
            {
                OnmanualSecondsChanging(value);
                ReportPropertyChanging("manualSeconds");
                _manualSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manualSeconds");
                OnmanualSecondsChanged();
            }
        }
        private global::System.String _manualSeconds;
        partial void OnmanualSecondsChanging(global::System.String value);
        partial void OnmanualSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String multiSeconds
        {
            get
            {
                return _multiSeconds;
            }
            set
            {
                OnmultiSecondsChanging(value);
                ReportPropertyChanging("multiSeconds");
                _multiSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("multiSeconds");
                OnmultiSecondsChanged();
            }
        }
        private global::System.String _multiSeconds;
        partial void OnmultiSecondsChanging(global::System.String value);
        partial void OnmultiSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notReadySeconds
        {
            get
            {
                return _notReadySeconds;
            }
            set
            {
                OnnotReadySecondsChanging(value);
                ReportPropertyChanging("notReadySeconds");
                _notReadySeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notReadySeconds");
                OnnotReadySecondsChanged();
            }
        }
        private global::System.String _notReadySeconds;
        partial void OnnotReadySecondsChanging(global::System.String value);
        partial void OnnotReadySecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfCallbacks
        {
            get
            {
                return _numberOfCallbacks;
            }
            set
            {
                OnnumberOfCallbacksChanging(value);
                ReportPropertyChanging("numberOfCallbacks");
                _numberOfCallbacks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfCallbacks");
                OnnumberOfCallbacksChanged();
            }
        }
        private global::System.String _numberOfCallbacks;
        partial void OnnumberOfCallbacksChanging(global::System.String value);
        partial void OnnumberOfCallbacksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfRefusals
        {
            get
            {
                return _numberOfRefusals;
            }
            set
            {
                OnnumberOfRefusalsChanging(value);
                ReportPropertyChanging("numberOfRefusals");
                _numberOfRefusals = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfRefusals");
                OnnumberOfRefusalsChanged();
            }
        }
        private global::System.String _numberOfRefusals;
        partial void OnnumberOfRefusalsChanging(global::System.String value);
        partial void OnnumberOfRefusalsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numberOfSuccesses
        {
            get
            {
                return _numberOfSuccesses;
            }
            set
            {
                OnnumberOfSuccessesChanging(value);
                ReportPropertyChanging("numberOfSuccesses");
                _numberOfSuccesses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numberOfSuccesses");
                OnnumberOfSuccessesChanged();
            }
        }
        private global::System.String _numberOfSuccesses;
        partial void OnnumberOfSuccessesChanging(global::System.String value);
        partial void OnnumberOfSuccessesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String otherSeconds
        {
            get
            {
                return _otherSeconds;
            }
            set
            {
                OnotherSecondsChanging(value);
                ReportPropertyChanging("otherSeconds");
                _otherSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("otherSeconds");
                OnotherSecondsChanged();
            }
        }
        private global::System.String _otherSeconds;
        partial void OnotherSecondsChanging(global::System.String value);
        partial void OnotherSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String parkSeconds
        {
            get
            {
                return _parkSeconds;
            }
            set
            {
                OnparkSecondsChanging(value);
                ReportPropertyChanging("parkSeconds");
                _parkSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("parkSeconds");
                OnparkSecondsChanged();
            }
        }
        private global::System.String _parkSeconds;
        partial void OnparkSecondsChanging(global::System.String value);
        partial void OnparkSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String previewSeconds
        {
            get
            {
                return _previewSeconds;
            }
            set
            {
                OnpreviewSecondsChanging(value);
                ReportPropertyChanging("previewSeconds");
                _previewSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("previewSeconds");
                OnpreviewSecondsChanged();
            }
        }
        private global::System.String _previewSeconds;
        partial void OnpreviewSecondsChanging(global::System.String value);
        partial void OnpreviewSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedCalls
        {
            get
            {
                return _reservedCalls;
            }
            set
            {
                OnreservedCallsChanging(value);
                ReportPropertyChanging("reservedCalls");
                _reservedCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedCalls");
                OnreservedCallsChanged();
            }
        }
        private global::System.String _reservedCalls;
        partial void OnreservedCallsChanging(global::System.String value);
        partial void OnreservedCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedCallsReceived
        {
            get
            {
                return _reservedCallsReceived;
            }
            set
            {
                OnreservedCallsReceivedChanging(value);
                ReportPropertyChanging("reservedCallsReceived");
                _reservedCallsReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedCallsReceived");
                OnreservedCallsReceivedChanged();
            }
        }
        private global::System.String _reservedCallsReceived;
        partial void OnreservedCallsReceivedChanging(global::System.String value);
        partial void OnreservedCallsReceivedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedSeconds
        {
            get
            {
                return _reservedSeconds;
            }
            set
            {
                OnreservedSecondsChanging(value);
                ReportPropertyChanging("reservedSeconds");
                _reservedSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedSeconds");
                OnreservedSecondsChanged();
            }
        }
        private global::System.String _reservedSeconds;
        partial void OnreservedSecondsChanging(global::System.String value);
        partial void OnreservedSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reservedSecondsReceived
        {
            get
            {
                return _reservedSecondsReceived;
            }
            set
            {
                OnreservedSecondsReceivedChanging(value);
                ReportPropertyChanging("reservedSecondsReceived");
                _reservedSecondsReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reservedSecondsReceived");
                OnreservedSecondsReceivedChanged();
            }
        }
        private global::System.String _reservedSecondsReceived;
        partial void OnreservedSecondsReceivedChanging(global::System.String value);
        partial void OnreservedSecondsReceivedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transferredCalls
        {
            get
            {
                return _transferredCalls;
            }
            set
            {
                OntransferredCallsChanging(value);
                ReportPropertyChanging("transferredCalls");
                _transferredCalls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transferredCalls");
                OntransferredCallsChanged();
            }
        }
        private global::System.String _transferredCalls;
        partial void OntransferredCallsChanging(global::System.String value);
        partial void OntransferredCallsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String workgroup
        {
            get
            {
                return _workgroup;
            }
            set
            {
                OnworkgroupChanging(value);
                ReportPropertyChanging("workgroup");
                _workgroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("workgroup");
                OnworkgroupChanged();
            }
        }
        private global::System.String _workgroup;
        partial void OnworkgroupChanging(global::System.String value);
        partial void OnworkgroupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wrapSeconds
        {
            get
            {
                return _wrapSeconds;
            }
            set
            {
                OnwrapSecondsChanging(value);
                ReportPropertyChanging("wrapSeconds");
                _wrapSeconds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wrapSeconds");
                OnwrapSecondsChanged();
            }
        }
        private global::System.String _wrapSeconds;
        partial void OnwrapSecondsChanging(global::System.String value);
        partial void OnwrapSecondsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptedCallsCount
        {
            get
            {
                return _acceptedCallsCount;
            }
            set
            {
                OnacceptedCallsCountChanging(value);
                ReportPropertyChanging("acceptedCallsCount");
                _acceptedCallsCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptedCallsCount");
                OnacceptedCallsCountChanged();
            }
        }
        private global::System.String _acceptedCallsCount;
        partial void OnacceptedCallsCountChanging(global::System.String value);
        partial void OnacceptedCallsCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rejectedCallsCount
        {
            get
            {
                return _rejectedCallsCount;
            }
            set
            {
                OnrejectedCallsCountChanging(value);
                ReportPropertyChanging("rejectedCallsCount");
                _rejectedCallsCount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rejectedCallsCount");
                OnrejectedCallsCountChanged();
            }
        }
        private global::System.String _rejectedCallsCount;
        partial void OnrejectedCallsCountChanging(global::System.String value);
        partial void OnrejectedCallsCountChanged();

        #endregion

    
    }

    #endregion

    
}
